manifestVersion: 1.1
id: pangolin
category: reverse-proxy
name: Pangolin
version: latest
tagline: Create secure, identity-aware connections to any resource.
description: Create secure, identity-aware connections to any resource. Combines VPN
  and reverse proxy for browser or client-based access with granular, zero-trust controls.
developer: fosrl
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://pangolin.net?utm_source=localhost
repo: https://github.com/fosrl/pangolin
support: https://docs.pangolin.net/self-host/manual/docker-compose
