services:
  mongodb:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - ./mongo-data:/data/db

  formio:
    image: formio/formio:latest
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - MONGO=mongodb://mongodb:27017/formio
      - ROOT_EMAIL=${ROOT_EMAIL}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
