services:
  pastefy:
    image: interaapps/pastefy:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PASTEFY_MONGODB_CONNECTION_STRING: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/pastefy?authSource=admin
      PASTEFY_REDIS_HOST: redis
      PASTEFY_REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:alpine
    restart: unless-stopped
