manifestVersion: 1.1
id: firefly-pico
category: budgeting
name: Firefly-Pico
version: latest
tagline: Log transactions effortlessly with a smart assistant.
description: Log transactions effortlessly with a smart assistant. This mobile-optimized
  PWA companion for Firefly III uses fuzzy search and templates for rapid expense
  tracking.
developer: cioraneanu
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/cioraneanu/firefly-pico?utm_source=localhost
repo: https://github.com/cioraneanu/firefly-pico
support: https://github.com/cioraneanu/firefly-pico/blob/main/docs/installation.md
