services:
  cherry:
    image: haishanh/cherry:latest
    container_name: cherry
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/cherry/data
    environment:
      - TZ=UTC
