services:
  watchyourlan:
    image: aceberg/watchyourlan
    container_name: watchyourlan
    network_mode: "host"
    restart: unless-stopped
    environment:
      - IFACE=eth0
      - TZ=UTC
      - GUIIP=0.0.0.0
      - GUIPORT=8840
      - SHOUTRRR_URL=${SHOUTRRR_URL}
    volumes:
      - ./data:/data/WatchYourLAN
