manifestVersion: 1.1
id: watchyourlan
category: ip-and-domain
name: WatchYourLAN
version: latest
tagline: Scan your local network to discover connected devices.
description: Scan your local network to discover connected devices. Receive instant
  notifications for new hosts, track online/offline history, and visualize data in
  Grafana.
developer: aceberg
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/aceberg/WatchYourLAN?utm_source=localhost
repo: https://github.com/aceberg/WatchYourLAN
support: https://github.com/aceberg/WatchYourLAN#quick-start
