services:
  cockpit:
    image: cockpithq/cockpit:latest
    container_name: cockpit
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./config:/var/www/html/config
      - ./storage:/var/www/html/storage
    environment:
      - COCKPIT_SESSION_NAME=cockpitsession
      - COCKPIT_SALT=${COCKPIT_SALT}
