manifestVersion: 1.1
id: gancio
category: poll-and-events
name: Gancio
version: latest
tagline: Organize local events with a privacy-first, shared agenda.
description: Organize local events with a privacy-first, shared agenda. Publish anonymously,
  avoid personal timelines, and export content freely across multiple platforms.
developer: Awesome Docker Compose
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://gancio.org?utm_source=localhost
repo: https://framagit.org/les/gancio
support: https://gancio.org/install/docker
