manifestVersion: 1.1
id: traccar
category: map-and-gps
name: Traccar
version: latest
tagline: Track any GPS device on a modern, open-source platform.
description: Track any GPS device on a modern, open-source platform. Get real-time
  views, detailed reports, and instant alerts for geo-fencing, driving behavior, and
  more.
developer: traccar
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.traccar.org?utm_source=localhost
repo: https://github.com/traccar/traccar
support: https://github.com/traccar/traccar-docker
