manifestVersion: 1.1
id: sosse
category: archiving
name: Sosse
version: '1.14'
tagline: Build a searchable web archive.
description: Build a searchable web archive. This open-source crawler indexes dynamic
  pages, downloads files, and integrates with external services via powerful webhooks.
developer: biolds
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://sosse.io?utm_source=localhost
repo: https://github.com/biolds/sosse
support: https://sosse.readthedocs.io/en/stable/install/docker.html
