services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

  cryptgeon:
    image: cupcakearmy/cryptgeon:latest
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      CRYPTGEON_REDIS_URL: "redis://redis:6379"
      CRYPTGEON_SIZE_LIMIT: "4 MiB"
      CRYPTGEON_CLEANUP_INTERVAL: "5 Minutes"
    ports:
      - 8000:5000
