manifestVersion: 1.1
id: corecontrol
category: system-monitoring
name: CoreControl
version: latest
tagline: Manage your entire server infrastructure from one place.
description: Manage your entire server infrastructure from one place. Add servers,
  track self-hosted apps with uptime monitoring, and visualize your network with flowcharts.
developer: crocofied
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/crocofied/CoreObs?utm_source=localhost
repo: https://github.com/crocofied/CoreObs
support: https://github.com/crocofied/CoreObs
