manifestVersion: 1.1
id: socialhome
category: social-network-and-forums
name: Socialhome
version: latest
tagline: Build a customizable, grid-based personal profile that connects directly
  to the federated social web.
description: Build a customizable, grid-based personal profile that connects directly
  to the federated social web. Share content, interact with others, and own your data.
developer: jaywink
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://socialhome.network?utm_source=awesome-docker-compose.com
repo: https://github.com/jaywink/socialhome
support: https://socialhome.readthedocs.io/en/latest/installation/docker.html
