manifestVersion: 1.1
id: dailytxt
category: note-taking-and-editor
name: DailyTxT
version: latest
tagline: Keep a private digital diary with server-side encryption.
description: Keep a private digital diary with server-side encryption. Self-host with
  Docker, upload files, write in Markdown, and organize entries with tags.
developer: PhiTux
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/PhiTux/DailyTxT?utm_source=localhost
repo: https://github.com/PhiTux/DailyTxT
support: https://github.com/PhiTux/DailyTxT#installation
