manifestVersion: 1.1
id: cops
category: e-books
name: COPS
version: latest
tagline: Access your ebook library anywhere with a lightweight OPDS and HTML server.
description: Access your ebook library anywhere with a lightweight OPDS and HTML server.
  Enjoy responsive design, fast search, and metadata updates on low-resource devices.
developer: mikespub-org
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://blog.slucas.fr/projects/calibre-opds-php-server?utm_source=awesome-docker-compose.com
repo: https://github.com/mikespub-org/seblucas-cops
support: https://github.com/linuxserver/docker-cops
