manifestVersion: 1.1
id: seaweedfs
category: object-storage-and-file-server
name: SeaweedFS
version: v2.21.0
tagline: Store and access billions of files instantly using a distributed storage
  system featuring O(1) disk read times, seamles...
description: Store and access billions of files instantly using a distributed storage
  system featuring O(1) disk read times, seamless cloud tiering, and S3 API support.
developer: seaweedfs
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://seaweedfs.com?utm_source=localhost
repo: https://github.com/seaweedfs/seaweedfs
support: https://github.com/seaweedfs/seaweedfs/blob/master/docker/seaweedfs-compose.yml
