manifestVersion: 1.1
id: task-keeper
category: task-management
name: Task Keeper
version: latest
tagline: Manage tasks and notes efficiently with a self-hosted list editor.
description: Manage tasks and notes efficiently with a self-hosted list editor. Use
  extensive keyboard shortcuts, tags, and collapsible items to organize your daily
  work.
developer: nymanjens
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/nymanjens/piga?utm_source=localhost
repo: https://github.com/nymanjens/piga
support: https://github.com/nymanjens/piga#installation-with-docker
