manifestVersion: 1.1
id: tuleap
category: project-management
name: Tuleap
version: latest
tagline: Manage software development and team collaboration with a single web-based
  solution.
description: Manage software development and team collaboration with a single web-based
  solution. Build and deploy projects efficiently with end-to-end traceability.
developer: Enalean
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.tuleap.com?utm_source=awesome-docker-compose.com
repo: https://github.com/Enalean/tuleap
support: https://docs.tuleap.com/installation-guide/docker/introduction.html
