manifestVersion: 1.1
id: feedless
category: rss
name: feedless
version: latest
tagline: Create custom RSS feeds from any website.
description: Create custom RSS feeds from any website. Filter existing feeds, merge
  multiple sources, and transform content to get the full text or track page changes.
developer: damoeb
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/damoeb/feedless?utm_source=localhost
repo: https://github.com/damoeb/feedless
support: https://github.com/damoeb/feedless/blob/master/docker-compose.prod.yml
