manifestVersion: 1.1
id: sshwifty
category: remote-access
name: Sshwifty
version: latest
tagline: Access SSH and Telnet services directly from your web browser.
description: Access SSH and Telnet services directly from your web browser. Deploy
  easily with Docker and configure connections with presets, hooks, and environment
  variables.
developer: nirui
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://sshwifty-demo.nirui.org?utm_source=localhost
repo: https://github.com/nirui/sshwifty
support: https://github.com/nirui/sshwifty#docker-image-recommended
