services:
  timetagger:
    image: ghcr.io/almarklein/timetagger:latest
    container_name: timetagger
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./data:/timetagger_data
