manifestVersion: 1.1
id: timetagger
category: time-tracking
name: TimeTagger
version: latest
tagline: Manage your hours using an interactive timeline and flexible tags.
description: Manage your hours using an interactive timeline and flexible tags. Generate
  detailed PDF reports, set productivity goals, and sync data across all devices.
developer: almarklein
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://timetagger.app?utm_source=localhost
repo: https://github.com/almarklein/timetagger
support: https://github.com/almarklein/timetagger#self-hosting-your-time-tracker
