manifestVersion: 1.1
id: jitsi-meet
category: video-conferencing
name: Jitsi Meet
version: stable
tagline: Host fully encrypted, open-source video meetings for free.
description: Host fully encrypted, open-source video meetings for free. Share screens,
  edit documents, and chat with no account required and no time limits.
developer: jitsi
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://jitsi.org/jitsi-meet?utm_source=awesome-docker-compose.com
repo: https://github.com/jitsi/jitsi-meet
support: https://github.com/jitsi/docker-jitsi-meet
