manifestVersion: 1.1
id: docker-mailserver
category: email-server
name: Docker Mailserver
version: latest
tagline: Deploy a production-ready, fullstack mail server using simple configuration
  files.
description: Deploy a production-ready, fullstack mail server using simple configuration
  files. Includes SMTP, IMAP, LDAP, anti-spam, and anti-virus without a database.
developer: docker-mailserver
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://docker-mailserver.github.io/docker-mailserver/latest?utm_source=localhost
repo: https://github.com/docker-mailserver/docker-mailserver
support: https://docker-mailserver.github.io/docker-mailserver/latest/examples/tutorials/basic-installation/
