manifestVersion: 1.1
id: anycable
category: custom-communication-system
name: AnyCable
version: latest
tagline: Add reliable two-way realtime communication to your backend using WebSockets
  and SSE.
description: Add reliable two-way realtime communication to your backend using WebSockets
  and SSE. Scale your applications efficiently with a robust, open-source server.
developer: anycable
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://anycable.io?utm_source=awesome-docker-compose.com
repo: https://github.com/anycable/anycable
support: https://docs.anycable.io/deployment/docker
