manifestVersion: 1.1
id: focalboard
category: project-management
name: Focalboard
version: latest
tagline: Centralize tasks, track milestones, and align technical teams with an open
  source project management platform featuring...
description: Centralize tasks, track milestones, and align technical teams with an
  open source project management platform featuring Kanban, calendar, and table views.
developer: mattermost-community
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.focalboard.com?utm_source=localhost
repo: https://github.com/mattermost-community/focalboard
support: https://www.focalboard.com/download/personal-edition/docker/
