manifestVersion: 1.1
id: listmonk
category: mailing-and-newsletter
name: listmonk
version: 13-alpine
tagline: Manage millions of subscribers and send fast email campaigns.
description: Manage millions of subscribers and send fast email campaigns. This self-hosted
  manager offers dynamic templates, built-in analytics, and multi-SMTP routing.
developer: knadh
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://listmonk.app?utm_source=awesome-docker-compose.com
repo: https://github.com/knadh/listmonk
support: https://listmonk.app/docs/installation/
