manifestVersion: 1.1
id: gollum
category: wiki
name: Gollum
version: latest
tagline: Build and manage wikis backed by version control.
description: Build and manage wikis backed by version control. Write in various markup
  languages, edit locally, and track changes easily with a built-in web interface.
developer: gollum
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/gollum/gollum?utm_source=localhost
repo: https://github.com/gollum/gollum
support: https://github.com/gollum/gollum/wiki/Gollum-via-Docker
