manifestVersion: 1.1
id: wallos
category: budgeting
name: Wallos
version: latest
tagline: Organize your subscriptions and manage expenses with a private, self-hosted
  tracker.
description: Organize your subscriptions and manage expenses with a private, self-hosted
  tracker. Get payment reminders, use multiple currencies, and keep your data secure.
developer: ellite
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://wallosapp.com?utm_source=localhost
repo: https://github.com/ellite/Wallos
support: https://github.com/ellite/Wallos#docker-1
