manifestVersion: 1.1
id: organizr
category: personal-dashboard
name: Organizr
version: latest
tagline: Organize all your HTPC and homelab services into a single, easy-to-use webpage.
description: Organize all your HTPC and homelab services into a single, easy-to-use
  webpage. Manage user access, customize tabs, and access everything from one interface.
developer: causefx
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/causefx/Organizr?utm_source=awesome-docker-compose.com
repo: https://github.com/causefx/Organizr
support: https://github.com/causefx/Organizr
