manifestVersion: 1.1
id: kimai
category: time-tracking
name: Kimai
version: '10.11'
tagline: Record work hours, analyze project budgets, and create custom invoices.
description: Record work hours, analyze project budgets, and create custom invoices.
  Secure your data with an open-source platform offering self-hosted and cloud options.
developer: kimai
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.kimai.org?utm_source=localhost
repo: https://github.com/kimai/kimai
support: https://www.kimai.org/documentation/docker-compose.html
