manifestVersion: 1.1
id: myspeed
category: speedtest
name: MySpeed
version: latest
tagline: Automatically test your internet speed 24/7.
description: Automatically test your internet speed 24/7. Track download, upload,
  and ping history with detailed analytics. A self-hosted, open-source solution for
  privacy.
developer: gnmyt
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://myspeed.dev?utm_source=awesome-docker-compose.com
repo: https://github.com/gnmyt/myspeed
support: https://docs.myspeed.dev/setup/linux
