manifestVersion: 1.1
id: umami
category: analytics
name: Umami
version: postgresql-latest
tagline: Umami is an open source, self-hosted web analytics solution.
description: Umami is an open source, self-hosted web analytics solution. It is a
  faster and privacy-focused alternative to Google Analytics. Umami is easy to set
  up and use, and it doesn't track any personal information of your visitors.
developer: umami-software
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://umami.is?utm_source=localhost
repo: https://github.com/umami-software/umami
support: https://github.com/umami-software/umami/blob/master/docker-compose.yml
