manifestVersion: 1.1
id: openproject
category: project-management
name: OpenProject
version: '13'
tagline: Manage classic, agile, or hybrid projects with complete data sovereignty.
description: Manage classic, agile, or hybrid projects with complete data sovereignty.
  Utilize Gantt charts, Kanban boards, and time tracking in a secure environment.
developer: opf
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.openproject.org?utm_source=awesome-docker-compose.com
repo: https://github.com/opf/openproject
support: https://github.com/opf/openproject-docker-compose
