services:
  lazywarden:
    image: querylab/lazywarden:latest
    container_name: lazywarden
    environment:
      - BW_HOST=${BW_HOST}
      - BW_CLIENTID=${BW_CLIENTID}
      - BW_CLIENTSECRET=${BW_CLIENTSECRET}
      - BW_PASSWORD=${BW_PASSWORD}
      - CRON_TIME=0 2 * * *
      - TZ=UTC
    volumes:
      - ./data:/backup
    restart: unless-stopped
