manifestVersion: 1.1
id: readflow
category: rss
name: readflow
version: latest
tagline: Centralize your news and articles in a single, simple app.
description: Centralize your news and articles in a single, simple app. Save content
  to read later on any device and enjoy a versatile reading experience with cloud
  integrations.
developer: ncarlier
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://readflow.app?utm_source=awesome-docker-compose.com
repo: https://github.com/ncarlier/readflow
support: https://github.com/ncarlier/readflow#installation
