manifestVersion: 1.1
id: aptabase
category: analytics
name: Aptabase
version: latest
tagline: Get real-time, anonymous insights for your apps.
description: Get real-time, anonymous insights for your apps. This open-source platform
  respects user privacy, ensures compliance, and offers lightweight SDKs for easy
  setup.
developer: aptabase
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://aptabase.com?utm_source=awesome-docker-compose.com
repo: https://github.com/aptabase/aptabase
support: https://github.com/aptabase/self-hosting
