manifestVersion: 1.1
id: archivy
category: archiving
name: Archivy
version: latest
tagline: Create a personal knowledge repository you control.
description: Create a personal knowledge repository you control. Save web pages, connect
  notes with bidirectional links, and manage everything in portable markdown files.
developer: archivy
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://archivy.github.io?utm_source=localhost
repo: https://github.com/archivy/archivy
support: https://github.com/archivy/archivy-docker
