manifestVersion: 1.1
id: christmas-community
category: poll-and-events
name: Christmas Community
version: latest
tagline: Manage family gift exchanges with shared wishlists.
description: Manage family gift exchanges with shared wishlists. Prevent double-gifting,
  track desired items, and customize lists for holidays, birthdays, or weddings.
developer: Wingysam
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/Wingysam/Christmas-Community?utm_source=localhost
repo: https://github.com/Wingysam/Christmas-Community
support: https://github.com/Wingysam/Christmas-Community#docker-compose
