manifestVersion: 1.1
id: loomio
category: social-network-and-forums
name: Loomio
version: 13-alpine
tagline: Facilitate asynchronous discussions and reach consensus faster.
description: Facilitate asynchronous discussions and reach consensus faster. Use expressive
  voting systems and time polls to make collaborative decisions without meetings.
developer: loomio
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.loomio.com?utm_source=localhost
repo: https://github.com/loomio/loomio
support: https://github.com/loomio/loomio-deploy
