manifestVersion: 1.1
id: bytebase
category: database-management
name: Bytebase
version: latest
tagline: Standardize database schema migrations using review workflows, SQL linting,
  and GitOps.
description: Standardize database schema migrations using review workflows, SQL linting,
  and GitOps. Secure data with just-in-time access, masking, and detailed audit logs.
developer: bytebase
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.bytebase.com?utm_source=localhost
repo: https://github.com/bytebase/bytebase
support: https://docs.bytebase.com/get-started/self-host/deploy-with-docker
