manifestVersion: 1.1
id: yt-dlp-web-ui
category: video-downloader
name: yt-dlp Web UI
version: latest
tagline: Get a simple web interface for the powerful yt-dlp tool.
description: Get a simple web interface for the powerful yt-dlp tool. Self-host your
  own video downloader and manage everything through your browser or the RPC server.
developer: marcopiovanello
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/marcopiovanello/yt-dlp-web-ui?utm_source=localhost
repo: https://github.com/marcopiovanello/yt-dlp-web-ui
support: https://gitea.aidystopia.xyz/marco/yt-dlp-webui
