manifestVersion: 1.1
id: librespeed
category: speedtest
name: LibreSpeed
version: latest
tagline: Test your internet connection's performance with a free and open-source tool.
description: Test your internet connection's performance with a free and open-source
  tool. Get accurate results for ping, jitter, download, and upload speeds without
  Flash or Java.
developer: librespeed
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://librespeed.org?utm_source=awesome-docker-compose.com
repo: https://github.com/librespeed/speedtest
support: https://github.com/librespeed/speedtest/blob/master/doc_docker.md
