manifestVersion: 1.1
id: chibisafe
category: quick-file-transfer
name: Chibisafe
version: latest
tagline: Save all your files in a beautiful, performant cloud vault.
description: Save all your files in a beautiful, performant cloud vault. This modern,
  self-hosted file uploading service features a fast API and chunked upload support.
developer: chibisafe
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://chibisafe.app?utm_source=awesome-docker-compose.com
repo: https://github.com/chibisafe/chibisafe
support: https://chibisafe.app/docs/installation/running-with-docker
