manifestVersion: 1.1
id: stalwart
category: email-server
name: Stalwart
version: latest
tagline: Deploy an all-in-one, Rust-based mail and collaboration server.
description: Deploy an all-in-one, Rust-based mail and collaboration server. Benefit
  from built-in spam filtering, modern protocols, and enterprise-grade security.
developer: stalwartlabs
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://stalw.art?utm_source=localhost
repo: https://github.com/stalwartlabs/stalwart
support: https://stalw.art/docs/install/platform/docker
