manifestVersion: 1.1
id: ghostfolio
category: budgeting
name: Ghostfolio
version: 15-alpine
tagline: Monitor your complete net worth with a private dashboard.
description: Monitor your complete net worth with a private dashboard. Track cash,
  stocks, ETFs, and cryptocurrencies from all your accounts in one place.
developer: ghostfolio
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://ghostfol.io?utm_source=localhost
repo: https://github.com/ghostfolio/ghostfolio
support: https://github.com/ghostfolio/ghostfolio#self-hosting
