manifestVersion: 1.1
id: joplin
category: note-taking-and-editor
name: Joplin
version: '15'
tagline: Capture multimedia notes, clip web pages, and sync across all devices.
description: Capture multimedia notes, clip web pages, and sync across all devices.
  Collaborate with others and customize your experience, all secured by E2EE.
developer: laurent22
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://joplinapp.org?utm_source=awesome-docker-compose.com
repo: https://github.com/laurent22/joplin
support: https://hub.docker.com/r/joplin/server
