services:
  yaade:
    image: esperotech/yaade:latest
    container_name: yaade
    ports:
      - 9339:9339
    volumes:
      - ./yaade-data:/app/data
    environment:
      - YAADE_ADMIN_USERNAME=${YAADE_ADMIN_USERNAME}
      - YAADE_ADMIN_PASSWORD=${YAADE_ADMIN_PASSWORD}
    restart: unless-stopped
