services:
  phplist:
    image: phplist/phplist
    restart: always
    ports:
      - "8000:80"
    environment:
      DB_HOST: mariadb
      DB_NAME: phplistdb
      DB_USER: phplist
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./phplist/config:/etc/phplist
      - ./phplist/images:/var/www/phpList/public_html/uploadimages
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: phplistdb
      MYSQL_USER: phplist
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql
