services:
  enigma-bbs:
    image: enigmabbs/enigma-bbs:latest
    container_name: enigma-bbs
    restart: unless-stopped
    ports:
      - "8888:8888" # Telnet
      - "8889:8889" # SSH
      - "8080:8080" # HTTP
      - "8443:8443" # HTTPS
    volumes:
      - ./config:/enigma-bbs/config
      - ./data/db:/enigma-bbs/db
      - ./data/filebase:/enigma-bbs/filebase
      - ./data/art:/enigma-bbs/art
      - ./data/logs:/enigma-bbs/logs
      - ./data/mods:/enigma-bbs/mods
      - ./data/mail:/enigma-bbs/mail
