manifestVersion: 1.1
id: enigma-bbs
category: social-network-and-forums
name: "ENiGMA\xBD BBS"
version: latest
tagline: Launch a highly customizable, multi-platform BBS featuring SSH access, legacy
  DOS door support, FidoNet integration, an...
description: Launch a highly customizable, multi-platform BBS featuring SSH access,
  legacy DOS door support, FidoNet integration, and a built-in achievement system.
developer: NuSkooler
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://nuskooler.github.io/enigma-bbs?utm_source=localhost
repo: https://github.com/NuSkooler/enigma-bbs
support: https://nuskooler.github.io/enigma-bbs/installation/docker.html
