manifestVersion: 1.1
id: stackstorm
category: automation
name: StackStorm
version: '4.4'
tagline: Connect all your apps and services to automate DevOps your way.
description: Connect all your apps and services to automate DevOps your way. Build
  simple rules or complex workflows for remediation, deployment, and security response.
developer: StackStorm
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://stackstorm.com?utm_source=localhost
repo: https://github.com/StackStorm/st2
support: https://github.com/stackstorm/st2-docker
