services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: fider

  app:
    image: getfider/fider:stable
    restart: always
    ports:
      - 3000:3000
    environment:
      GO_ENV: production
      DATABASE_URL: postgres://fider:${DB_PASSWORD}@db:5432/fider?sslmode=disable
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_NOREPLY: ${EMAIL_NOREPLY}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
      EMAIL_SMTP_PASS: ${EMAIL_SMTP_PASS}
      BASE_URL: ${BASE_URL}
    depends_on:
      - db
