manifestVersion: 1.1
id: dpaste
category: pastebin
name: Dpaste
version: latest
tagline: Share code snippets easily with this open-source pastebin application.
description: Share code snippets easily with this open-source pastebin application.
  Run it standalone or integrate it directly into your existing Django environments.
developer: DarrenOfficial
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://dpaste.org?utm_source=localhost
repo: https://github.com/DarrenOfficial/dpaste
support: https://docs.dpaste.org/installation/
