manifestVersion: 1.1
id: picsur
category: image-hosting
name: Picsur
version: latest
tagline: Create your own image sharing platform.
description: Create your own image sharing platform. Upload, convert, and edit images
  in various formats. Manage users with roles, strip EXIF data, and deploy easily
  with Docker.
developer: CaramelFur
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/CaramelFur/Picsur?utm_source=localhost
repo: https://github.com/CaramelFur/Picsur
support: https://github.com/CaramelFur/Picsur#running-your-own-instance
