manifestVersion: 1.1
id: briefkasten
category: bookmark-manager
name: Briefkasten
version: 15-alpine
tagline: Stop losing track of important links.
description: Stop losing track of important links. Save any webpage, organize it into
  collections, and find exactly what you need, whenever you need it.
developer: ndom91
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://briefkastenhq.com?utm_source=awesome-docker-compose.com
repo: https://github.com/ndom91/briefkasten
support: https://docs.briefkastenhq.com/docs/self-hosting
