manifestVersion: 1.1
id: dufs
category: storage-file-transfer
name: Dufs
version: latest
tagline: Deploy a versatile file server to host static assets, manage drag-and-drop
  uploads, and enforce access controls.
description: Deploy a versatile file server to host static assets, manage drag-and-drop
  uploads, and enforce access controls. Includes WebDAV, search, and HTTPS support.
developer: sigoden
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/sigoden/dufs?utm_source=localhost
repo: https://github.com/sigoden/dufs
support: https://github.com/sigoden/dufs
