manifestVersion: 1.1
id: transfer-sh
category: quick-file-transfer
name: transfer.sh
version: latest
tagline: Share files instantly from your terminal.
description: Share files instantly from your terminal. Encrypt uploads, set download
  limits, scan for viruses, and host your own instance with multiple storage backends.
developer: dutchcoders
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/dutchcoders/transfer.sh?utm_source=localhost
repo: https://github.com/dutchcoders/transfer.sh
support: https://github.com/dutchcoders/transfer.sh#docker
