manifestVersion: 1.1
id: portkey
category: personal-dashboard
name: Portkey
version: latest
tagline: Create a simple, self-hosted startup page for your links.
description: Create a simple, self-hosted startup page for your links. Display link
  collections, add custom pages, and manage it all with one configuration file.
developer: kodehat
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://demo.portkey.page?utm_source=localhost
repo: https://github.com/kodehat/portkey
support: https://github.com/kodehat/portkey#docker
