services:
  postgresql:
    image: bitnami/postgresql:16
    restart: always
    environment:
      - POSTGRESQL_USERNAME=bn_discourse
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=bitnami_discourse
    volumes:
      - ./data/postgresql:/bitnami/postgresql

  redis:
    image: bitnami/redis:7.2
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/bitnami/redis/data

  discourse:
    image: bitnami/discourse:3
    restart: always
    ports:
      - "80:3000"
    environment:
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_PASSWORD=${POSTGRESQL_PASSWORD}
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - DISCOURSE_REDIS_PASSWORD=${REDIS_PASSWORD}
      - DISCOURSE_HOST=localhost
      - DISCOURSE_USERNAME=admin
      - DISCOURSE_PASSWORD=${DISCOURSE_ADMIN_PASSWORD}
      - DISCOURSE_EMAIL=admin@example.com
    volumes:
      - ./data/discourse:/bitnami/discourse
    depends_on:
      - postgresql
      - redis

  sidekiq:
    image: bitnami/discourse:3
    restart: always
    command: /opt/bitnami/scripts/discourse/sidekiq.sh
    environment:
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_PASSWORD=${POSTGRESQL_PASSWORD}
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - DISCOURSE_REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./data/discourse:/bitnami/discourse
    depends_on:
      - discourse
