manifestVersion: 1.1
id: recipya
category: recipe-management
name: Recipya
version: latest
tagline: Manage your favorite meals with a clean, powerful recipe manager designed
  for the whole family.
description: Manage your favorite meals with a clean, powerful recipe manager designed
  for the whole family. Easily organize, save, and share your culinary creations.
developer: reaper47
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://old.recipya.ca?utm_source=localhost
repo: https://github.com/reaper47/recipya
support: https://old.recipya.ca/docs/installation/docker/
