manifestVersion: 1.1
id: bentopdf
category: office-suite
name: BentoPDF
version: latest
tagline: Access over 100 free PDF tools directly in your browser.
description: Access over 100 free PDF tools directly in your browser. Merge, split,
  and compress files with complete privacy. No uploads or signups are ever required.
developer: alam00000
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://bentopdf.com?utm_source=awesome-docker-compose.com
repo: https://github.com/alam00000/bentopdf
support: https://bentopdf.com/docs/self-hosting/docker
