manifestVersion: 1.1
id: ente
category: photo-server
name: Ente
version: latest
tagline: Protect your photos with end-to-end encryption.
description: Protect your photos with end-to-end encryption. This open-source tool
  offers cross-platform access, family plans, and AI features without compromising
  privacy.
developer: ente-io
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://ente.io?utm_source=awesome-docker-compose.com
repo: https://github.com/ente-io/ente
support: https://github.com/ente-io/ente/blob/main/docs/docs/self-hosting/index.md
