manifestVersion: 1.1
id: automatisch
category: automation
name: Automatisch
version: 13-alpine
tagline: Build no-code automations and connect your apps.
description: Build no-code automations and connect your apps. Choose between a cloud
  plan or self-hosting for complete data privacy and no vendor lock-in.
developer: automatisch
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://automatisch.io?utm_source=localhost
repo: https://github.com/automatisch/automatisch
support: https://automatisch.io/docs/guide/installation
