manifestVersion: 1.1
id: filerise
category: storage-file-transfer
name: FileRise
version: latest
tagline: Manage files securely on your own servers.
description: Manage files securely on your own servers. Connect multiple storage sources,
  set granular access controls, and build branded client upload portals easily.
developer: error311
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://filerise.net?utm_source=localhost
repo: https://github.com/error311/FileRise
support: https://github.com/error311/FileRise/wiki/install-setup
