manifestVersion: 1.1
id: warpgate
category: remote-access
name: Warpgate
version: latest
tagline: Secure internal SSH, HTTPS, and database servers with SSO and RBAC.
description: Secure internal SSH, HTTPS, and database servers with SSO and RBAC. This
  open-source tool requires no client apps and provides full session recording.
developer: warp-tech
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://warpgate.null.page?utm_source=localhost
repo: https://github.com/warp-tech/warpgate
support: https://warpgate.null.page/getting-started-on-docker/
