services:
  hatsu:
    image: ghcr.io/importantimport/hatsu:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/hatsu/data
    environment:
      - HATSU_DOMAIN=${HATSU_DOMAIN}
      - HATSU_LISTEN_HOST=0.0.0.0
      - HATSU_LISTEN_PORT=3000
      - DATABASE_URL=sqlite:///hatsu/data/hatsu.sqlite
