manifestVersion: 1.1
id: gotosocial
category: social-network-and-forums
name: GoToSocial
version: latest
tagline: Launch a lightweight, customizable social server.
description: Launch a lightweight, customizable social server. Connect across the
  Fediverse without algorithms or tracking, using minimal memory and CPU resources.
developer: Awesome Docker Compose
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://docs.gotosocial.org?utm_source=localhost
repo: https://codeberg.org/superseriousbusiness/gotosocial
support: https://docs.gotosocial.org/en/latest/getting_started/installation/container/
