manifestVersion: 1.1
id: wordpress
category: blogging-platform
name: WordPress
version: '8.0'
tagline: Create any website, blog, or app with an open-source publishing platform.
description: Create any website, blog, or app with an open-source publishing platform.
  Customize every detail using intuitive design tools and thousands of extensions.
developer: Awesome Docker Compose
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://wordpress.org?utm_source=awesome-docker-compose.com
repo: https://awesome-docker-compose.com/wordpress
support: https://awesome-docker-compose.com/wordpress
