manifestVersion: 1.1
id: flame
category: personal-dashboard
name: Flame
version: latest
tagline: Create a personal startpage for your server.
description: Create a personal startpage for your server. Easily manage applications
  and bookmarks with built-in editors, a powerful search, and Docker integration.
developer: pawelmalak
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/pawelmalak/flame?utm_source=localhost
repo: https://github.com/pawelmalak/flame
support: https://github.com/pawelmalak/flame#installation
