manifestVersion: 1.1
id: rustdesk
category: remote-access
name: RustDesk
version: latest
tagline: Get secure, open-source remote access.
description: Get secure, open-source remote access. Host your own server for complete
  data sovereignty, enhanced security, and full customization. Works on all major
  platforms.
developer: rustdesk
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://rustdesk.com?utm_source=awesome-docker-compose.com
repo: https://github.com/rustdesk/rustdesk-server
support: https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/docker/
