manifestVersion: 1.1
id: cloudbeaver
category: database-management
name: CloudBeaver
version: latest
tagline: Access and manage 100+ databases.
description: Access and manage 100+ databases. Use advanced tools for SQL development,
  data analysis, schema design, and secure administration in one unified application.
developer: dbeaver
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://dbeaver.com?utm_source=localhost
repo: https://github.com/dbeaver/cloudbeaver
support: https://github.com/dbeaver/cloudbeaver/wiki/
