manifestVersion: 1.1
id: gossa
category: storage-file-transfer
name: gossa
version: latest
tagline: Manage and share multimedia files using a fast, dependency-free server.
description: Manage and share multimedia files using a fast, dependency-free server.
  Enjoy drag-and-drop uploads, video streaming, and a highly responsive web interface.
developer: pldubouilh
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/pldubouilh/gossa?utm_source=localhost
repo: https://github.com/pldubouilh/gossa
support: https://github.com/pldubouilh/gossa#fancier-setups
