manifestVersion: 1.1
id: teamspeak
category: custom-communication-system
name: TeamSpeak
version: latest
tagline: Communicate with crystal-clear, lag-free audio using a highly secure, decentralized
  VoIP platform.
description: Communicate with crystal-clear, lag-free audio using a highly secure,
  decentralized VoIP platform. Enjoy 3D surround sound and advanced permission controls.
developer: TeamSpeak-Systems
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://teamspeak.com?utm_source=awesome-docker-compose.com
repo: https://github.com/TeamSpeak-Systems/teamspeak-linux-docker-images
support: https://github.com/TeamSpeak-Systems/teamspeak-linux-docker-images
