manifestVersion: 1.1
id: stirling-pdf
category: document-management
name: Stirling-PDF
version: latest
tagline: Process sensitive documents securely on your own infrastructure.
description: Process sensitive documents securely on your own infrastructure. Deploy
  an air-gapped, AI-native platform to edit, redact, and automate PDFs with zero leaks.
developer: Stirling-Tools
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.stirling.com?utm_source=awesome-docker-compose.com
repo: https://github.com/Stirling-Tools/Stirling-PDF
support: https://github.com/Stirling-Tools/Stirling-PDF#quick-start
