services:
  perlite:
    image: secure77/perlite:latest
    container_name: perlite
    ports:
      - "80:80"
    volumes:
      - ./Obsidian:/var/www/perlite/Obsidian
    environment:
      - NOTES_DIR=Obsidian
      - SITE_TITLE=Perlite
      - HIDE_FOLDERS=.obsidian,.git,.trash
    restart: unless-stopped
