services:
  gladys:
    image: gladysassistant/gladys:v4
    container_name: gladys
    restart: always
    privileged: true
    network_mode: host
    environment:
      NODE_ENV: production
      SERVER_PORT: 80
      TZ: Europe/Paris
    volumes:
      - ./gladys-data:/var/lib/gladysassistant
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
