manifestVersion: 1.1
id: gladys-assistant
category: internet-of-things-iot
name: Gladys Assistant
version: v4
tagline: Automate your smart home with a privacy-first platform.
description: Automate your smart home with a privacy-first platform. Manage devices
  from a clean dashboard, create routines, and keep all your data stored locally.
developer: GladysAssistant
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://gladysassistant.com?utm_source=localhost
repo: https://github.com/GladysAssistant/Gladys
support: https://gladysassistant.com/docs/installation/docker-compose/
