manifestVersion: 1.1
id: mindsdb
category: database-management
name: MindsDB
version: latest
tagline: Query structured and unstructured data using natural language.
description: Query structured and unstructured data using natural language. Get real-time,
  trustworthy analytics from over 200 sources without moving data or waiting for analysts.
developer: mindsdb
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://mindsdb.com?utm_source=localhost
repo: https://github.com/mindsdb/mindsdb
support: https://docs.mindsdb.com/setup/self-hosted/docker
