services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync:latest
    container_name: adguardhome-sync
    environment:
      - ORIGIN_URL=http://192.168.1.10:80
      - ORIGIN_USERNAME=${ORIGIN_USERNAME}
      - ORIGIN_PASSWORD=${ORIGIN_PASSWORD}
      - REPLICA_URL=http://192.168.1.11:80
      - REPLICA_USERNAME=${REPLICA_USERNAME}
      - REPLICA_PASSWORD=${REPLICA_PASSWORD}
      - CRON=*/10 * * * *
      - RUN_ON_START=true
    restart: unless-stopped
