manifestVersion: 1.1
id: traefik
category: web-server
name: Traefik
version: v3.0
tagline: Dynamically route and load balance your microservices with a modern reverse
  proxy.
description: Dynamically route and load balance your microservices with a modern reverse
  proxy. Automates service discovery, ingress control, and SSL certificate management.
developer: traefik
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://traefik.io/traefik?utm_source=localhost
repo: https://github.com/traefik/traefik
support: https://doc.traefik.io/traefik/getting-started/install-traefik/
