manifestVersion: 1.1
id: zincsearch
category: search-engine-solution
name: ZincSearch
version: latest
tagline: Get a powerful full-text search engine in a single binary.
description: Get a powerful full-text search engine in a single binary. A lightweight
  alternative to Elasticsearch with compatible APIs for easy data ingestion.
developer: zincsearch
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://zincsearch-docs.zinc.dev?utm_source=awesome-docker-compose.com
repo: https://github.com/zincsearch/zincsearch
support: https://zincsearch-docs.zinc.dev/installation/
