manifestVersion: 1.1
id: docuseal
category: document-management
name: DocuSeal
version: latest
tagline: Collect legally binding e-signatures and build custom document workflows.
description: Collect legally binding e-signatures and build custom document workflows.
  Integrate seamlessly into any app using robust open-source developer tools.
developer: docusealco
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.docuseal.com?utm_source=awesome-docker-compose.com
repo: https://github.com/docusealco/docuseal
support: https://github.com/docusealco/docuseal#deploy
