manifestVersion: 1.1
id: srs
category: video-streaming
name: SRS
version: '6'
tagline: Build real-time video platforms with a high-efficiency media server.
description: Build real-time video platforms with a high-efficiency media server.
  Supports RTMP, WebRTC, HLS, SRT, and MPEG-DASH for versatile streaming solutions.
developer: ossrs
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/ossrs/srs?utm_source=awesome-docker-compose.com
repo: https://github.com/ossrs/srs
support: https://ossrs.io/lts/en-us/docs/v6/doc/getting-started
