manifestVersion: 1.1
id: otter-wiki
category: wiki
name: Otter Wiki
version: '2'
tagline: Build and manage documentation using a minimalistic, Git-backed wiki.
description: Build and manage documentation using a minimalistic, Git-backed wiki.
  Features include an advanced Markdown editor, version tracking, and user authentication.
developer: redimp
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://otterwiki.com?utm_source=localhost
repo: https://github.com/redimp/otterwiki
support: https://otterwiki.com/Installation
