manifestVersion: 1.1
id: cloudflare-ddns
category: dns
name: Cloudflare DDNS
version: latest
tagline: Automatically update Cloudflare DNS records for dynamic IPs.
description: Automatically update Cloudflare DNS records for dynamic IPs. Features
  IPv4/IPv6 support, proxy control, WAF list management, and robust security features.
developer: favonia
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/favonia/cloudflare-ddns?utm_source=awesome-docker-compose.com
repo: https://github.com/favonia/cloudflare-ddns
support: https://github.com/favonia/cloudflare-ddns#%EF%B8%8F-quick-start
