services:
  alerthub:
    image: ardakilic/alerthub:latest
    container_name: alerthub
    restart: unless-stopped
    volumes:
      - ./config.js:/app/config.js
      - ./data/db.json:/app/db.json
    environment:
      - TZ=${TZ}
