services:
  livestreamdvr:
    image: ghcr.io/mrbrax/twitchautomator:latest
    container_name: livestreamdvr
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./vods:/app/public/vods
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
