manifestVersion: 1.1
id: livestreamdvr
category: archiving
name: LiveStreamDVR
version: latest
tagline: Automatically record livestreams with chat and metadata.
description: Automatically record livestreams with chat and metadata. Save VODs, cut
  clips, and export to multiple destinations. Get instant notifications when streams
  go live.
developer: MrBrax
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/MrBrax/LiveStreamDVR?utm_source=localhost
repo: https://github.com/MrBrax/LiveStreamDVR
support: https://github.com/MrBrax/LiveStreamDVR#docker-setup
