manifestVersion: 1.1
id: podfetch
category: podcasting
name: PodFetch
version: latest
tagline: Manage your audio experience with a lightweight, self-hosted podcast manager.
description: Manage your audio experience with a lightweight, self-hosted podcast
  manager. Download, search, organize feeds, and sync playback across all your devices.
developer: SamTV12345
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://podfetch-docs.samtv.fyi?utm_source=awesome-docker-compose.com
repo: https://github.com/SamTV12345/PodFetch
support: https://podfetch-docs.samtv.fyi/Installation.html
