services:
  yarn:
    image: prologic/yarnd:latest
    container_name: yarn
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - YARN_DATA=/data
      - YARN_STORE=bitcask:///data/yarn.db
      - YARN_URL=http://localhost:8000
      - YARN_COOKIE_SECRET=${YARN_COOKIE_SECRET}
      - YARN_ADMIN_USER=${YARN_ADMIN_USER}
      - YARN_ADMIN_PASSWORD=${YARN_ADMIN_PASSWORD}
