manifestVersion: 1.1
id: yarn-social
category: social-network-and-forums
name: Yarn.social
version: latest
tagline: Host your own social feed on a decentralized, privacy-first platform.
description: Host your own social feed on a decentralized, privacy-first platform.
  Connect with others through micro-blogging without ads, tracking, or data collection.
developer: Awesome Docker Compose
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://yarn.social?utm_source=awesome-docker-compose.com
repo: https://git.mills.io/yarnsocial/yarn
support: https://git.mills.io/yarnsocial/yarn#deploy-with-docker
