manifestVersion: 1.1
id: roundup-issue-tracker
category: ticketing
name: Roundup Issue Tracker
version: latest
tagline: Manage bugs, support tickets, and sales leads with a highly customizable
  tracking system.
description: Manage bugs, support tickets, and sales leads with a highly customizable
  tracking system. Access via web, command-line, REST, XML-RPC, or email interfaces.
developer: Awesome Docker Compose
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.roundup-tracker.org?utm_source=awesome-docker-compose.com
repo: https://www.roundup-tracker.org/docs/installation.html#running-your-container
support: https://www.roundup-tracker.org/docs/installation.html#running-your-container
