manifestVersion: 1.1
id: db-backup
category: database-backup
name: db-backup
version: latest
tagline: Run scheduled backups for various databases in a single Docker container.
description: Run scheduled backups for various databases in a single Docker container.
  Customize jobs with compression, encryption, and store them locally, on S3, or Azure.
developer: tiredofit
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/tiredofit/docker-db-backup?utm_source=awesome-docker-compose.com
repo: https://github.com/tiredofit/docker-db-backup
support: https://github.com/tiredofit/docker-db-backup#configuration
