manifestVersion: 1.1
id: statusnook
category: network-monitoring
name: Statusnook
version: latest
tagline: Deploy a self-hosted status page to monitor endpoints in minutes.
description: Deploy a self-hosted status page to monitor endpoints in minutes. Communicate
  incidents and maintenance with your users via email and Slack. Simple setup.
developer: goksan
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://statusnook.com?utm_source=localhost
repo: https://github.com/goksan/statusnook
support: https://github.com/goksan/statusnook#docker
