manifestVersion: 1.1
id: sonic
category: search-engine-solution
name: Sonic
version: latest
tagline: Add fast, schema-less search to your application.
description: Add fast, schema-less search to your application. This lightweight backend
  offers typo correction and auto-completion while running on just a few megabytes
  of RAM.
developer: valeriansaliou
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/valeriansaliou/sonic?utm_source=localhost
repo: https://github.com/valeriansaliou/sonic
support: https://github.com/valeriansaliou/sonic#installation
