manifestVersion: 1.1
id: spacebin
category: pastebin
name: Spacebin
version: latest
tagline: Share notes, code snippets, and text documents easily.
description: Share notes, code snippets, and text documents easily. Built with Go
  for maximum reliability, this lightweight server ensures your data is always accessible.
developer: lukewhrit
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://spaceb.in?utm_source=awesome-docker-compose.com
repo: https://github.com/lukewhrit/spacebin
support: https://github.com/lukewhrit/spacebin#documentation
