manifestVersion: 1.1
id: squirrel-servers-manager
category: system-monitoring
name: Squirrel Servers Manager
version: latest
tagline: Simplify server and container management with an open-source dashboard.
description: Simplify server and container management with an open-source dashboard.
  Harness the power of Ansible and Docker through an intuitive, agentless interface.
developer: SquirrelCorporation
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://squirrelserversmanager.io?utm_source=awesome-docker-compose.com
repo: https://github.com/SquirrelCorporation/SquirrelServersManager
support: https://github.com/SquirrelCorporation/SquirrelServersManager/blob/master/docker-compose.yml
