manifestVersion: 1.1
id: rudderstack
category: analytics
name: RudderStack
version: 11-alpine
tagline: Collect high-quality customer data from every source.
description: Collect high-quality customer data from every source. Deliver it in real-time
  to your entire stack to power analytics, marketing, and AI with full privacy control.
developer: rudderlabs
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.rudderstack.com?utm_source=awesome-docker-compose.com
repo: https://github.com/rudderlabs/rudder-server
support: https://www.rudderstack.com/docs/get-started/rudderstack-open-source/data-plane-setup/docker/
