manifestVersion: 1.1
id: offen
category: analytics
name: Offen
version: latest
tagline: Gain valuable website insights with a self-hosted, open-source tool.
description: Gain valuable website insights with a self-hosted, open-source tool.
  Give users full access and control over their data. GDPR compliant and opt-in only.
developer: offen
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.offen.dev?utm_source=localhost
repo: https://github.com/offen/offen
support: https://docs.offen.dev/running-offen/tutorials/configuring-deploying-offen-docker/
