manifestVersion: 1.1
id: scm-manager
category: git-server
name: SCM-Manager
version: latest
tagline: Manage Git, Mercurial, and Subversion repositories from a single interface.
description: Manage Git, Mercurial, and Subversion repositories from a single interface.
  Install easily, extend with plugins, and integrate with a rich REST API.
developer: scm-manager
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://scm-manager.org?utm_source=localhost
repo: https://github.com/scm-manager/scm-manager
support: https://scm-manager.org/docs/latest/en/installation/docker/
