manifestVersion: 1.1
id: mirotalk-sfu
category: video-conferencing
name: MiroTalk SFU
version: latest
tagline: Connect instantly with free, secure video calls directly in your browser.
description: Connect instantly with free, secure video calls directly in your browser.
  Enjoy screen sharing, recording, interactive whiteboards, and AI-powered features.
developer: miroslavpejic85
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://sfu.mirotalk.com?utm_source=localhost
repo: https://github.com/miroslavpejic85/mirotalksfu
support: https://docs.mirotalk.com/mirotalk-sfu/self-hosting/
