services:
  tyk-gateway:
    image: tykio/tyk-gateway:latest
    ports:
      - "8080:8080"
    networks:
      - tyk
    environment:
      - TYK_GW_SECRET=${TYK_GW_SECRET}
      - TYK_GW_REDIS_HOST=tyk-redis
      - TYK_GW_REDIS_PORT=6379
    volumes:
      - ./apps:/opt/tyk-gateway/apps
      - ./certs:/opt/tyk-gateway/certs
      - ./middleware:/opt/tyk-gateway/middleware
    depends_on:
      - tyk-redis

  tyk-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - tyk
    volumes:
      - ./redis-data:/data

networks:
  tyk:
