manifestVersion: 1.1
id: kyoo
category: media-server
name: Kyoo
version: latest
tagline: Manage your personal media library with a portable platform that tracks watch
  history, organizes content by genre, and...
description: Manage your personal media library with a portable platform that tracks
  watch history, organizes content by genre, and offers personalized recommendations.
developer: zoriya
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://kyoo.zoriya.dev?utm_source=awesome-docker-compose.com
repo: https://github.com/zoriya/kyoo
support: https://github.com/zoriya/Kyoo/blob/master/INSTALLING.md
