manifestVersion: 1.1
id: scrutiny
category: system-monitoring
name: Scrutiny
version: master-omnibus
tagline: Monitor hard drive health with a web UI.
description: Monitor hard drive health with a web UI. Track historical S.M.A.R.T.
  data, use real-world failure thresholds, and receive timely notifications to prevent
  data loss.
developer: AnalogJ
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/AnalogJ/scrutiny?utm_source=awesome-docker-compose.com
repo: https://github.com/AnalogJ/scrutiny
support: https://github.com/AnalogJ/scrutiny#docker
