manifestVersion: 1.1
id: nhost
category: paas
name: Nhost
version: 15-alpine
tagline: Build and deploy a scalable backend in minutes.
description: Build and deploy a scalable backend in minutes. Get a complete stack
  with a local CLI, Git-based CI/CD, and managed infrastructure for rapid development.
developer: nhost
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://nhost.io?utm_source=localhost
repo: https://github.com/nhost/nhost
support: https://github.com/nhost/nhost/tree/main/examples/docker-compose
