manifestVersion: 1.1
id: slash
category: url-shortener
name: Slash
version: latest
tagline: Host your own platform to organize and share frequently used links.
description: Host your own platform to organize and share frequently used links. Create
  custom shortcuts, track traffic analytics, and access URLs via browser extensions.
developer: yourselfhosted
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/yourselfhosted/slash?utm_source=awesome-docker-compose.com
repo: https://github.com/yourselfhosted/slash
support: https://github.com/yourselfhosted/slash/blob/main/docs/install.md
