services:
  paaster:
    image: wardpearce/paaster:latest
    container_name: paaster
    restart: unless-stopped
    ports:
      - 8000:80
    environment:
      - MONGO_URI=mongodb://mongo:27017/paaster
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: paaster_mongo
    restart: unless-stopped
    volumes:
      - ./mongo-data:/data/db
