services:
  concourse-db:
    image: postgres:15
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /database
    volumes:
      - ./database:/database

  concourse-web:
    image: concourse/concourse
    command: web
    depends_on:
      - concourse-db
    ports:
      - "8080:8080"
    volumes:
      - ./keys/web:/concourse-keys
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: ${CONCOURSE_USER}:${CONCOURSE_PASSWORD}
      CONCOURSE_MAIN_TEAM_LOCAL_USER: ${CONCOURSE_USER}

  concourse-worker:
    image: concourse/concourse
    privileged: true
    command: worker
    stop_signal: SIGUSR2
    depends_on:
      - concourse-web
    environment:
      CONCOURSE_TSA_HOST: concourse-web:2222
    volumes:
      - ./keys/worker:/concourse-keys
