manifestVersion: 1.1
id: concourse
category: ci-and-cd
name: Concourse
version: '15'
tagline: Create powerful, container-based CI/CD pipelines using simple YAML.
description: Create powerful, container-based CI/CD pipelines using simple YAML. Visualize
  your entire workflow, get reproducible builds, and debug failures with direct container
  access.
developer: concourse
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://concourse-ci.org?utm_source=awesome-docker-compose.com
repo: https://github.com/concourse/concourse
support: https://github.com/concourse/concourse-docker
