services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db-data:/var/lib/postgresql/data

  exbin:
    image: m1dnight/exbin:latest
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - HOSTNAME=${HOSTNAME}
      - PORT=4000
    depends_on:
      - db
