services:
  app:
    image: heyform/community:latest
    container_name: heyform
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/heyform
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_HOMEPAGE_URL=${APP_HOMEPAGE_URL}
      - SESSION_KEY=${SESSION_KEY}
      - FORM_ENCRYPTION_KEY=${FORM_ENCRYPTION_KEY}
      - MAIL_SMTP_HOST=${MAIL_SMTP_HOST}
      - MAIL_SMTP_PORT=${MAIL_SMTP_PORT}
      - MAIL_SMTP_USER=${MAIL_SMTP_USER}
      - MAIL_SMTP_PASS=${MAIL_SMTP_PASS}
      - MAIL_SMTP_SECURE=${MAIL_SMTP_SECURE}
      - MAIL_FROM=${MAIL_FROM}
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    volumes:
      - ./mongo-data:/data/db

  redis:
    image: redis:6.0
    container_name: redis
    restart: always
