manifestVersion: 1.1
id: heyform
category: poll-and-events
name: HeyForm
version: latest
tagline: Build custom surveys and interactive polls using an open-source form builder.
description: Build custom surveys and interactive polls using an open-source form
  builder. Apply conditional logic, match your brand, and connect with your favorite
  apps.
developer: heyform
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://heyform.net?utm_source=awesome-docker-compose.com
repo: https://github.com/heyform/heyform
support: https://docs.heyform.net/open-source/self-hosting
