manifestVersion: 1.1
id: metabase
category: analytics
name: Metabase
version: latest
tagline: Enable anyone to explore data with no-code tools and AI.
description: Enable anyone to explore data with no-code tools and AI. Create dashboards,
  ask questions in natural language, and embed analytics into your application.
developer: metabase
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.metabase.com?utm_source=localhost
repo: https://github.com/metabase/metabase
support: https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker
