manifestVersion: 1.1
id: stash
category: media-server
name: Stash
version: latest
tagline: Organize, tag, and stream your personal adult media privately.
description: Organize, tag, and stream your personal adult media privately. Create
  galleries, bookmark favorite scenes, and scrape metadata securely on your local
  network.
developer: stashapp
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://stashapp.cc?utm_source=localhost
repo: https://github.com/stashapp/stash
support: https://docs.stashapp.cc/installation/docker/
