manifestVersion: 1.1
id: rss-bridge
category: rss
name: RSS-Bridge
version: latest
tagline: Create custom RSS feeds for hundreds of websites that don't offer them.
description: Create custom RSS feeds for hundreds of websites that don't offer them.
  Follow social media, news sites, and more in your favorite feed reader.
developer: RSS-Bridge
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://rss-bridge.org/bridge01?utm_source=awesome-docker-compose.com
repo: https://github.com/RSS-Bridge/rss-bridge
support: https://github.com/RSS-Bridge/rss-bridge#install-from-docker-hub
