manifestVersion: 1.1
id: commafeed
category: rss
name: CommaFeed
version: latest
tagline: Discover a free, open-source RSS reader inspired by Google Reader.
description: Discover a free, open-source RSS reader inspired by Google Reader. Organize
  your favorite feeds, read them online, and enjoy a clean, clutter-free interface.
developer: Athou
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.commafeed.com?utm_source=localhost
repo: https://github.com/Athou/commafeed
support: https://github.com/Athou/commafeed
