manifestVersion: 1.1
id: claper
category: poll-and-events
name: Claper
version: latest
tagline: Turn presentations into two-way conversations using live polls, Q&A, and
  quizzes.
description: Turn presentations into two-way conversations using live polls, Q&A,
  and quizzes. Upload existing slides and gather instant feedback from your audience.
developer: ClaperCo
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://claper.co?utm_source=localhost
repo: https://github.com/ClaperCo/Claper
support: https://github.com/ClaperCo/Claper/blob/dev/docker-compose.yml
