manifestVersion: 1.1
id: eda
category: analytics
name: EDA
version: latest
tagline: Connect your database and get insights in minutes.
description: Connect your database and get insights in minutes. Build interactive
  reports and dashboards with drag-and-drop ease. No coding or technical knowledge
  is required.
developer: jortilles
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://eda.jortilles.com?utm_source=localhost
repo: https://github.com/jortilles/EDA
support: https://github.com/jortilles/EDA#-run-edalitics-with-docker-recommended
