manifestVersion: 1.1
id: inventree
category: inventory-management
name: InvenTree
version: stable
tagline: Manage parts, track stock, and organize suppliers with this open-source inventory
  system.
description: Manage parts, track stock, and organize suppliers with this open-source
  inventory system. Features include BOM management and custom plugin integrations.
developer: inventree
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://inventree.org?utm_source=localhost
repo: https://github.com/inventree/InvenTree
support: https://docs.inventree.org/en/latest/start/docker_install/
