manifestVersion: 1.1
id: linuxgsm
category: games
name: LinuxGSM
version: latest
tagline: Manage dedicated Linux game servers effortlessly using a simple command-line
  interface.
description: Manage dedicated Linux game servers effortlessly using a simple command-line
  interface. Automate updates, monitor performance, and receive instant crash alerts.
developer: GameServerManagers
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://linuxgsm.com?utm_source=awesome-docker-compose.com
repo: https://github.com/GameServerManagers/LinuxGSM
support: https://github.com/GameServerManagers/docker-gameserver
