manifestVersion: 1.1
id: snikket
category: xmpp
name: Snikket
version: '1'
tagline: Communicate safely on a decentralized messaging network.
description: Communicate safely on a decentralized messaging network. Create private
  groups, make audio or video calls, and keep your data completely under your control.
developer: snikket-im
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://snikket.org?utm_source=localhost
repo: https://github.com/snikket-im/snikket-server
support: https://snikket.org/service/quickstart/
