manifestVersion: 1.1
id: onedev
category: git-server
name: OneDev
version: latest
tagline: Run a self-hosted DevOps platform with Git, CI/CD, Kanban, and package management.
description: Run a self-hosted DevOps platform with Git, CI/CD, Kanban, and package
  management. Automate workflows, track issues, and manage your entire dev lifecycle.
developer: theonedev
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://onedev.io?utm_source=awesome-docker-compose.com
repo: https://github.com/theonedev/onedev
support: https://docs.onedev.io/
