services:
  server:
    image: padloc/server:latest
    container_name: padloc_server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PL_PWA_URL=http://localhost:8080
      - PL_SERVER_URL=http://localhost:3000
      - PL_DATA_DIR=/data
      - PL_EMAIL_SERVER=${PL_EMAIL_SERVER}
      - PL_EMAIL_PORT=587
      - PL_EMAIL_USER=${PL_EMAIL_USER}
      - PL_EMAIL_PASSWORD=${PL_EMAIL_PASSWORD}
      - PL_EMAIL_FROM=${PL_EMAIL_FROM}
    volumes:
      - ./server-data:/data

  pwa:
    image: padloc/pwa:latest
    container_name: padloc_pwa
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PL_SERVER_URL=http://localhost:3000
