manifestVersion: 1.1
id: padloc
category: password-manager
name: Padloc
version: latest
tagline: Securely store passwords, notes, credit cards, and files with end-to-end
  encryption.
description: Securely store passwords, notes, credit cards, and files with end-to-end
  encryption. Access your data on any device and share it safely with your family
  or team.
developer: padloc
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://padloc.app?utm_source=awesome-docker-compose.com
repo: https://github.com/padloc/padloc
support: https://github.com/padloc/padloc/tree/main/docs/examples/hosting/docker
