manifestVersion: 1.1
id: searxng
category: internet-tool
name: SearXNG
version: alpine
tagline: Search the internet securely without being tracked or profiled.
description: Search the internet securely without being tracked or profiled. This
  open-source metasearch engine aggregates results from over 200 sources with full
  privacy.
developer: searxng
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://docs.searxng.org?utm_source=awesome-docker-compose.com
repo: https://github.com/searxng/searxng
support: https://github.com/searxng/searxng-docker
