manifestVersion: 1.1
id: traggo
category: time-tracking
name: Traggo
version: latest
tagline: Track your time using a flexible tag system instead of rigid tasks.
description: Track your time using a flexible tag system instead of rigid tasks. Host
  it yourself to maintain absolute privacy and visualize data on custom dashboards.
developer: traggo
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://traggo.net?utm_source=awesome-docker-compose.com
repo: https://github.com/traggo/server
support: https://traggo.net/install/
