services:
  mysql:
    image: mysql:5.7
    container_name: leantime_mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: leantime
      MYSQL_USER: leantime
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always

  leantime:
    image: leantime/leantime:latest
    container_name: leantime_app
    environment:
      LEAN_DB_HOST: mysql
      LEAN_DB_USER: leantime
      LEAN_DB_PASSWORD: ${DB_PASSWORD}
      LEAN_DB_DATABASE: leantime
      LEAN_APP_URL: http://localhost:8080
    ports:
      - 8080:80
    volumes:
      - ./data/public_userfiles:/var/www/html/public/userfiles
      - ./data/userfiles:/var/www/html/userfiles
    depends_on:
      - mysql
    restart: always
