services:
  pwpush:
    image: pglombardo/pwpush:latest
    container_name: pwpush
    environment:
      - DATABASE_URL=postgresql://pwpush:${DB_PASSWORD}@db:5432/pwpush
    ports:
      - "5100:5100"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:alpine
    container_name: pwpush-db
    environment:
      - POSTGRES_USER=pwpush
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=pwpush
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: unless-stopped
