manifestVersion: 1.1
id: dozzle
category: container-management
name: Dozzle
version: latest
tagline: Monitor container logs in real-time with a lightweight, open-source, and
  secure viewer.
description: Monitor container logs in real-time with a lightweight, open-source,
  and secure viewer. Self-host to keep your logs private. Supports Docker and Podman.
developer: amir20
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://dozzle.dev?utm_source=localhost
repo: https://github.com/amir20/dozzle
support: https://dozzle.dev/guide/getting-started
