manifestVersion: 1.1
id: zusam
category: social-network-and-forums
name: Zusam
version: latest
tagline: Build a private social hub for friends and family.
description: Build a private social hub for friends and family. Share messages, upload
  videos, create photo albums, and generate rich link previews on a secure server.
developer: zusam
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/zusam/zusam?utm_source=awesome-docker-compose.com
repo: https://github.com/zusam/zusam
support: https://github.com/zusam/zusam/blob/master/documentation/docker.md
