manifestVersion: 1.1
id: bracket
category: poll-and-events
name: Bracket
version: latest
tagline: Build tournament setups, schedule matches, track scores, and present live
  rankings to the public with this free, open-s...
description: Build tournament setups, schedule matches, track scores, and present
  live rankings to the public with this free, open-source management system.
developer: evroon
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://docs.bracketapp.nl?utm_source=localhost
repo: https://github.com/evroon/bracket
support: https://docs.bracketapp.nl/docs/deployment/docker/
