services:
  rapidbay:
    image: hauxir/rapidbay:latest
    container_name: rapidbay
    ports:
      - "5000:5000"
    environment:
      - RAPIDBAY_PASSWORD=${RAPIDBAY_PASSWORD}
    volumes:
      - ./data:/tmp
    restart: unless-stopped
