manifestVersion: 1.1
id: flaresolverr
category: proxy
name: FlareSolverr
version: latest
tagline: Bypass Cloudflare and DDoS-GUARD protections using a proxy server.
description: Bypass Cloudflare and DDoS-GUARD protections using a proxy server. It
  launches a headless browser to solve challenges and returns usable HTML and cookies.
developer: FlareSolverr
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/FlareSolverr/FlareSolverr?utm_source=awesome-docker-compose.com
repo: https://github.com/FlareSolverr/FlareSolverr
support: https://github.com/FlareSolverr/FlareSolverr#docker
