manifestVersion: 1.1
id: coder
category: ide-and-tools
name: Coder
version: latest
tagline: Run AI coding agents at scale within secure, self-hosted environments.
description: Run AI coding agents at scale within secure, self-hosted environments.
  Gain full control over permissions, compliance, and audit logs on your own infrastructure.
developer: coder
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://coder.com?utm_source=awesome-docker-compose.com
repo: https://github.com/coder/coder
support: https://coder.com/docs/install/docker
