services:
  statping:
    container_name: statping
    image: ghcr.io/statping-ng/statping-ng:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app
    environment:
      - IS_DOCKER=true
      - DB_CONN=sqlite
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
