manifestVersion: 1.1
id: mistborn
category: self-hosting-solution
name: Mistborn
version: latest
tagline: Manage self-hosted services in a personal virtual cloud.
description: Manage self-hosted services in a personal virtual cloud. Secure apps
  with a firewall, Wireguard VPN with PiHole, IP filtering, and optional SIEM+IDS.
developer: Awesome Docker Compose
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://gitlab.com/cyber5k/mistborn?utm_source=awesome-docker-compose.com
repo: https://gitlab.com/cyber5k/mistborn
support: https://gitlab.com/cyber5k/mistborn#installation
