services:
  polaris:
    image: ogarcia/polaris:latest
    container_name: polaris
    restart: unless-stopped
    ports:
      - "5050:5050"
    volumes:
      - ./music:/music
      - ./data:/var/lib/polaris
      - ./cache:/var/cache/polaris
