services:
  pictshare:
    image: ghcr.io/hascheksolutions/pictshare
    container_name: pictshare
    ports:
      - "8080:80"
    volumes:
      - ./data:/data
    environment:
      - TITLE=PictShare
      - MAX_UPLOAD_SIZE=50M
      - UPLOAD_CODE=${UPLOAD_CODE}
    restart: unless-stopped
