manifestVersion: 1.1
id: castopod
category: podcasting
name: Castopod
version: latest
tagline: Launch and manage your podcasts with a free, open-source hosting platform.
description: Launch and manage your podcasts with a free, open-source hosting platform.
  Interact directly with your listeners and build a highly engaged community.
developer: ad-aures
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://castopod.org?utm_source=localhost
repo: https://github.com/ad-aures/castopod
support: https://docs.castopod.org/main/en/getting-started/docker/
