manifestVersion: 1.1
id: mastodon
category: social-network-and-forums
name: Mastodon
version: 14-alpine
tagline: Join a decentralized, open-source social network.
description: Join a decentralized, open-source social network. Experience an ad-free,
  chronological feed, community-led moderation, and full control over your audience.
developer: mastodon
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://joinmastodon.org?utm_source=awesome-docker-compose.com
repo: https://github.com/mastodon/mastodon
support: https://github.com/mastodon/mastodon/blob/main/docker-compose.yml
