manifestVersion: 1.1
id: xbackbone
category: quick-file-transfer
name: XBackBone
version: latest
tagline: Manage and share files instantly with a lightweight PHP file manager.
description: Manage and share files instantly with a lightweight PHP file manager.
  Enjoy multi-user support, media previews, and seamless cloud storage integration.
developer: SergiX44
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://xbackbone.app?utm_source=localhost
repo: https://github.com/SergiX44/XBackBone
support: https://github.com/linuxserver/docker-xbackbone
