services:
  ovenmediaengine:
    image: airensoft/ovenmediaengine:latest
    container_name: ovenmediaengine
    restart: unless-stopped
    environment:
      - TZ=UTC
    ports:
      - "1935:1935"
      - "3333:3333"
      - "3334:3334"
      - "3478:3478"
      - "3478:3478/udp"
      - "4000:4000/udp"
      - "8080:8080"
      - "8090:8090"
      - "9000:9000"
      - "10000-10010:10000-10010/udp"
    volumes:
      - ./conf:/opt/ovenmediaengine/bin/origin_conf
