manifestVersion: 1.1
id: simplelogin
category: email-server
name: SimpleLogin
version: '13'
tagline: Shield your real inbox from spam and phishing using anonymous email aliases.
description: Shield your real inbox from spam and phishing using anonymous email aliases.
  Send and receive messages securely while keeping your online identity hidden.
developer: simple-login
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://simplelogin.io?utm_source=awesome-docker-compose.com
repo: https://github.com/simple-login/app
support: https://github.com/simple-login/app#run-simplelogin-docker-containers
