manifestVersion: 1.1
id: input
category: poll-and-events
name: Input
version: latest
tagline: Manage projects from start to finish with intuitive task tracking, automated
  workflows, and seamless team collaboration...
description: Manage projects from start to finish with intuitive task tracking, automated
  workflows, and seamless team collaboration features designed for modern teams.
developer: deck9
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://getinput.co?utm_source=awesome-docker-compose.com
repo: https://github.com/deck9/input
support: https://github.com/deck9/input#production-deployment
