manifestVersion: 1.1
id: wizarr
category: arr
name: Wizarr
version: latest
tagline: Automate user invitations for Plex, Jellyfin, and Emby.
description: Automate user invitations for Plex, Jellyfin, and Emby. Generate secure
  links, manage membership durations, and guide users through client setup.
developer: Wizarrrr
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://docs.wizarr.dev?utm_source=localhost
repo: https://github.com/Wizarrrr/wizarr
support: https://docs.wizarr.dev/getting-started/installation
