manifestVersion: 1.1
id: heimdall
category: personal-dashboard
name: Heimdall
version: latest
tagline: Create a single, elegant dashboard for all your web applications and links.
description: Create a single, elegant dashboard for all your web applications and
  links. Add generic items or use pre-configured apps with API integration for extra
  info.
developer: linuxserver
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://heimdall.site?utm_source=localhost
repo: https://github.com/linuxserver/Heimdall
support: https://github.com/linuxserver/Heimdall
