services:
  stump:
    image: aaronleopold/stump:latest
    container_name: stump
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./media:/media
    ports:
      - 10801:10801
