manifestVersion: 1.1
id: stump
category: e-books
name: Stump
version: latest
tagline: Curate and host your comic books, manga, and digital libraries on a lightning-fast
  server.
description: Curate and host your comic books, manga, and digital libraries on a lightning-fast
  server. Sync reading progress across devices and read offline anywhere.
developer: stumpapp
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.stumpapp.dev?utm_source=localhost
repo: https://github.com/stumpapp/stump
support: https://www.stumpapp.dev/installation/docker
