manifestVersion: 1.1
id: lazytainer
category: container-management
name: Lazytainer
version: master
tagline: Monitor network traffic to automatically stop and start Docker containers.
description: Monitor network traffic to automatically stop and start Docker containers.
  Save resources by only running services when they are actively being used.
developer: vmorganp
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/vmorganp/Lazytainer?utm_source=awesome-docker-compose.com
repo: https://github.com/vmorganp/Lazytainer
support: https://github.com/vmorganp/Lazytainer/blob/master/docker-compose.yaml
