services:
  app:
    container_name: filestash
    image: machines/filestash
    restart: always
    environment:
      - APPLICATION_URL=${APPLICATION_URL}
      - ONLYOFFICE_URL=http://onlyoffice
    ports:
      - "8334:8334"
    volumes:
      - ./data/state:/app/data/state
    depends_on:
      - onlyoffice

  onlyoffice:
    container_name: filestash_onlyoffice
    image: onlyoffice/documentserver
    restart: always
