manifestVersion: 1.1
id: glance
category: personal-dashboard
name: Glance
version: latest
tagline: Create a personal, self-hosted dashboard to view all your feeds in one place.
description: Create a personal, self-hosted dashboard to view all your feeds in one
  place. Aggregate RSS, Reddit, YouTube, and more with highly customizable widgets.
developer: glanceapp
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/glanceapp/glance?utm_source=awesome-docker-compose.com
repo: https://github.com/glanceapp/glance
support: https://github.com/glanceapp/glance#docker
