services:
  mikochi:
    image: zer0tonin/mikochi:latest
    container_name: mikochi
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./files:/data
    environment:
      - USERNAME=${MIKOCHI_USERNAME}
      - PASSWORD=${MIKOCHI_PASSWORD}
