manifestVersion: 1.1
id: snips-sh
category: pastebin
name: snips.sh
version: latest
tagline: Share code snippets directly from your terminal via SSH.
description: Share code snippets directly from your terminal via SSH. Manage files
  anonymously, generate time-limited URLs, and view syntax-highlighted code on the
  web.
developer: robherley
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://snips.sh?utm_source=awesome-docker-compose.com
repo: https://github.com/robherley/snips.sh
support: https://github.com/robherley/snips.sh/blob/main/docs/self-hosting.md
