services:
  nominatim:
    image: mediagis/nominatim:4.3
    container_name: nominatim
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PBF_URL=https://download.geofabrik.de/europe/monaco-latest.osm.pbf
      - REPLICATION_URL=https://download.geofabrik.de/europe/monaco-updates/
      - IMPORT_WIKIPEDIA=false
      - NOMINATIM_PASSWORD=${NOMINATIM_PASSWORD}
    volumes:
      - ./nominatim-data:/var/lib/postgresql/14/main
    shm_size: 1gb
