manifestVersion: 1.1
id: yopass
category: pastebin
name: Yopass
version: alpine
tagline: Securely share passwords, API keys, and sensitive data using end-to-end encryption.
description: Securely share passwords, API keys, and sensitive data using end-to-end
  encryption. Create one-time, self-destructing links to keep your information safe.
developer: jhaals
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://yopass.se?utm_source=localhost
repo: https://github.com/jhaals/yopass
support: https://github.com/jhaals/yopass#installation--configuration
