manifestVersion: 1.1
id: dashy
category: personal-dashboard
name: Dashy
version: latest
tagline: Build a personal dashboard for your homelab.
description: Build a personal dashboard for your homelab. Customize layouts, add widgets,
  monitor service status, and manage access with built-in authentication.
developer: lissy93
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://dashy.to?utm_source=localhost
repo: https://github.com/lissy93/dashy
support: https://dashy.to/docs/deployment/#using-docker-compose
