manifestVersion: 1.1
id: web-check
category: ip-and-domain
name: Web-Check
version: latest
tagline: Get deep insights into any website.
description: Get deep insights into any website. Analyze IP info, SSL, DNS, headers,
  open ports, and security configurations to understand, optimize, and secure your
  site.
developer: lissy93
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://web-check.xyz?utm_source=localhost
repo: https://github.com/lissy93/web-check
support: https://github.com/lissy93/web-check#configuring
