manifestVersion: 1.1
id: node-red
category: internet-of-things-iot
name: Node-RED
version: latest
tagline: Build event-driven applications using a low-code approach.
description: Build event-driven applications using a low-code approach. Easily collect,
  transform, and visualize real-time data for home automation or industrial systems.
developer: node-red
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://nodered.org?utm_source=localhost
repo: https://github.com/node-red/node-red
support: https://nodered.org/docs/getting-started/docker
