manifestVersion: 1.1
id: plik
category: quick-file-transfer
name: Plik
version: latest
tagline: Share files quickly using a temporary upload service.
description: Share files quickly using a temporary upload service. Protect your data
  with custom expiration limits, password protection, and secure download links.
developer: root-gg
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://plik.root.gg?utm_source=localhost
repo: https://github.com/root-gg/plik
support: https://root-gg.github.io/plik/guide/docker.html
