services:
  web:
    container_name: plane-web
    image: makeplane/plane-frontend:latest
    restart: always
    command: /usr/local/bin/start.sh
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      NEXT_PUBLIC_GOOGLE_CLIENTID: "0"
      NEXT_PUBLIC_GITHUB_ID: "0"
      NEXT_PUBLIC_GITLAB_APP_ID: "0"
      NEXT_PUBLIC_SENTRY_DSN: ""
      NEXT_PUBLIC_ENABLE_SENTRY: "0"
    depends_on:
      - api
      - worker

  api:
    container_name: plane-api
    image: makeplane/plane-backend:latest
    restart: always
    command: ./bin/takeoff
    environment:
      DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:5432/${PGDATABASE}
      REDIS_URL: redis://${REDIS_HOST}:6379/
      SECRET_KEY: ${SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      FILE_SIZE_LIMIT: 5242880
      WEB_URL: ${WEB_URL}
      GITHUB_CLIENT_SECRET: ""
      DISABLE_COLLECTSTATIC: 1
      DOCKERIZED: 1
    depends_on:
      - db
      - redis
      - minio

  worker:
    container_name: plane-worker
    image: makeplane/plane-backend:latest
    restart: always
    command: ./bin/worker
    environment:
      DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:5432/${PGDATABASE}
      REDIS_URL: redis://${REDIS_HOST}:6379/
      SECRET_KEY: ${SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      FILE_SIZE_LIMIT: 5242880
      WEB_URL: ${WEB_URL}
      DOCKERIZED: 1
    depends_on:
      - api
      - db
      - redis
      - minio

  beat:
    container_name: plane-beat
    image: makeplane/plane-backend:latest
    restart: always
    command: ./bin/beat
    environment:
      DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:5432/${PGDATABASE}
      REDIS_URL: redis://${REDIS_HOST}:6379/
      SECRET_KEY: ${SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      FILE_SIZE_LIMIT: 5242880
      WEB_URL: ${WEB_URL}
      DOCKERIZED: 1
    depends_on:
      - api
      - db
      - redis
      - minio

  migrator:
    container_name: plane-migrator
    image: makeplane/plane-backend:latest
    restart: no
    command: ./bin/migrate
    environment:
      DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:5432/${PGDATABASE}
      REDIS_URL: redis://${REDIS_HOST}:6379/
      SECRET_KEY: ${SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      DOCKERIZED: 1
    depends_on:
      - db
      - redis
      - minio

  proxy:
    container_name: plane-proxy
    image: makeplane/plane-proxy:latest
    restart: always
    ports:
      - ${APP_PORT:-80}:80
    environment:
      FILE_SIZE_LIMIT: 5242880
      BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
    depends_on:
      - web
      - api

  db:
    container_name: plane-db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    container_name: plane-redis
    image: redis:7-alpine
    restart: always
    volumes:
      - ./data/redis:/data

  minio:
    container_name: plane-minio
    image: minio/minio
    restart: always
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./data/minio:/data
