manifestVersion: 1.1
id: plane
category: project-management
name: Plane
version: latest
tagline: Plan and execute work with flexible views, built-in documentation, and AI
  agents.
description: Plan and execute work with flexible views, built-in documentation, and
  AI agents. Manage projects securely with cloud, self-hosted, or air-gapped deployments.
developer: makeplane
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://plane.so?utm_source=awesome-docker-compose.com
repo: https://github.com/makeplane/plane
support: https://developers.plane.so/self-hosting/methods/docker-compose
