services:
  kener:
    image: rajnandan1/kener:latest
    container_name: kener
    environment:
      - TZ=UTC
      - NODE_ENV=production
      - GH_TOKEN=${GH_TOKEN}
      - API_TOKEN=${API_TOKEN}
    ports:
      - "3000:3000"
    volumes:
      - ./config:/config
    restart: unless-stopped
