manifestVersion: 1.1
id: kener
category: network-monitoring
name: Kener
version: latest
tagline: Build and host a beautiful status page for your services.
description: Build and host a beautiful status page for your services. This open-source
  system uses Svelte and TailwindCSS to keep your users informed and updated.
developer: rajnandan1
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://kener.ing?utm_source=localhost
repo: https://github.com/rajnandan1/kener
support: https://kener.ing/docs/deployment
