manifestVersion: 1.1
id: upstat
category: network-monitoring
name: Upstat
version: latest
tagline: Monitor your website and API uptime with a self-hosted tool.
description: Monitor your website and API uptime with a self-hosted tool. Get instant
  alerts for performance issues and keep users informed with status pages.
developer: chamanbravo
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://upstat.vercel.app?utm_source=awesome-docker-compose.com
repo: https://github.com/chamanbravo/upstat
support: https://github.com/chamanbravo/upstat#-how-to-install
