services:
  chhoto-url:
    image: sintan1729/chhoto-url:latest
    container_name: chhoto-url
    restart: unless-stopped
    ports:
      - "4567:4567"
    volumes:
      - ./data:/data
    environment:
      - DATABASE_URL=sqlite:///data/urls.sqlite
      - PASSWORD=${APP_PASSWORD}
