manifestVersion: 1.1
id: black-candy
category: music-server
name: Black Candy
version: latest
tagline: Host your own music streaming server using Docker.
description: Host your own music streaming server using Docker. Manage media files,
  integrate with Discogs for album art, and listen on the go with dedicated mobile
  apps.
developer: blackcandy-org
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/blackcandy-org/blackcandy?utm_source=localhost
repo: https://github.com/blackcandy-org/blackcandy
support: https://github.com/blackcandy-org/blackcandy#installation
