manifestVersion: 1.1
id: minecraft-papermc-server
category: games
name: Minecraft PaperMC Server
version: latest
tagline: Launch a high-performance Minecraft server using container technology.
description: Launch a high-performance Minecraft server using container technology.
  Run it seamlessly on AMD64 or ARM64 platforms, including Raspberry Pi and Synology
  NAS.
developer: mtoensing
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server?utm_source=awesome-docker-compose.com
repo: https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server
support: https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server#quick-start
