manifestVersion: 1.1
id: docassemble
category: poll-and-events
name: Docassemble
version: latest
tagline: Create guided interviews and automate document assembly using an open-source
  expert system based on Python.
description: Create guided interviews and automate document assembly using an open-source
  expert system based on Python. Features AI, SMS, live chat, and secure APIs.
developer: jhpyle
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://docassemble.org?utm_source=awesome-docker-compose.com
repo: https://github.com/jhpyle/docassemble
support: https://docassemble.org/docs/docker.html
