manifestVersion: 1.1
id: shifter
category: quick-file-transfer
name: Shifter
version: latest
tagline: Host your own file-sharing platform.
description: Host your own file-sharing platform. Upload files, generate shareable
  links, automatically zip multiple files, and set automatic expiration dates for
  security.
developer: TobySuch
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/TobySuch/Shifter?utm_source=awesome-docker-compose.com
repo: https://github.com/TobySuch/Shifter
support: https://github.com/TobySuch/Shifter#running-in-production
