services:
  bitwarden:
    image: bitwarden/self-host:latest
    container_name: bitwarden
    restart: always
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      BW_DOMAIN: "https://bitwarden.example.com"
      BW_DB_PROVIDER: "sqlite"
      BW_DB_FILE: "/etc/bitwarden/bwdata/core/attachments/db.sqlite3"
      BW_INSTALLATION_ID: "${BW_INSTALLATION_ID}"
      BW_INSTALLATION_KEY: "${BW_INSTALLATION_KEY}"
      adminSettings__admins: "${ADMIN_EMAIL}"
    volumes:
      - ./bwdata:/etc/bitwarden/bwdata
