manifestVersion: 1.1
id: bitwarden
category: password-manager
name: Bitwarden
version: latest
tagline: Securely manage passwords and passkeys for personal or business use.
description: Securely manage passwords and passkeys for personal or business use.
  Generate, save, and autofill credentials across all devices with open-source, audited
  security.
developer: bitwarden
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://bitwarden.com?utm_source=awesome-docker-compose.com
repo: https://github.com/bitwarden/server
support: https://bitwarden.com/help/install-and-deploy-lite/
