manifestVersion: 1.1
id: thingsboard
category: internet-of-things-iot
name: ThingsBoard
version: latest
tagline: Manage IoT devices, collect telemetry data, and build real-time dashboards.
description: Manage IoT devices, collect telemetry data, and build real-time dashboards.
  This open-source platform offers fault-tolerant processing and high scalability.
developer: thingsboard
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://thingsboard.io?utm_source=localhost
repo: https://github.com/thingsboard/thingsboard
support: https://thingsboard.io/docs/user-guide/install/docker/
