services:
  tracks:
    image: tracksapp/tracks:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql2://tracks:${DB_PASSWORD}@db/tracks
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RAILS_SERVE_STATIC_FILES=true
      - TZ=UTC
    depends_on:
      - db
    volumes:
      - ./data/assets:/usr/src/app/public/assets

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=tracks
      - MYSQL_USER=tracks
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
