manifestVersion: 1.1
id: satisfactory-server
category: games
name: Satisfactory Server
version: latest
tagline: Run a dedicated multiplayer server for your favorite factory building game
  using Docker.
description: Run a dedicated multiplayer server for your favorite factory building
  game using Docker. Enjoy automatic updates, easy backups, and full modding support.
developer: wolveix
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/wolveix/satisfactory-server?utm_source=localhost
repo: https://github.com/wolveix/satisfactory-server
support: https://github.com/wolveix/satisfactory-server#setup
