manifestVersion: 1.1
id: kanboard
category: task-management
name: Kanboard
version: latest
tagline: Manage projects with a free, open-source Kanban board.
description: Manage projects with a free, open-source Kanban board. Visualize tasks,
  limit work in progress, and automate workflows using a minimalist interface.
developer: kanboard
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://kanboard.org?utm_source=awesome-docker-compose.com
repo: https://github.com/kanboard/kanboard
support: https://docs.kanboard.org/v1/admin/docker/
