manifestVersion: 1.1
id: collabora
category: office-suite
name: Collabora
version: latest
tagline: Edit documents, spreadsheets, and presentations online with your team.
description: Edit documents, spreadsheets, and presentations online with your team.
  This open-source suite integrates into your infrastructure for complete data control
  and security.
developer: CollaboraOnline
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.collaboraonline.com?utm_source=awesome-docker-compose.com
repo: https://github.com/CollaboraOnline/online
support: https://www.collaboraonline.com/code/#learnmorecode
