manifestVersion: 1.1
id: druid
category: analytics
name: Druid
version: '15'
tagline: Execute OLAP queries in milliseconds on trillions of rows.
description: Execute OLAP queries in milliseconds on trillions of rows. Build highly
  concurrent applications with native integration for Kafka and Kinesis.
developer: apache
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://druid.apache.org?utm_source=localhost
repo: https://github.com/apache/druid
support: https://druid.apache.org/docs/latest/tutorials/docker/
