services:
  mirotalk-p2p:
    image: mirotalk/p2p:latest
    container_name: mirotalk-p2p
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - API_KEY_SECRET=${API_KEY_SECRET}
