manifestVersion: 1.1
id: mediawiki
category: wiki
name: MediaWiki
version: stable
tagline: Collect, organize, and share knowledge using a highly customizable, free
  wiki system.
description: Collect, organize, and share knowledge using a highly customizable, free
  wiki system. Build a reliable collaboration and documentation platform for any project.
developer: wikimedia
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.mediawiki.org?utm_source=localhost
repo: https://github.com/wikimedia/mediawiki
support: https://github.com/wikimedia/mediawiki-docker
