manifestVersion: 1.1
id: teampass
category: password-manager
name: TeamPass
version: latest
tagline: Securely manage and share team passwords with a self-hosted solution.
description: Securely manage and share team passwords with a self-hosted solution.
  Organize credentials, define user roles, and protect sensitive data with robust
  encryption.
developer: nilsteampassnet
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://teampass.net?utm_source=localhost
repo: https://github.com/nilsteampassnet/TeamPass
support: https://github.com/nilsteampassnet/TeamPass#documentation
