services:
  centrifugo:
    image: centrifugo/centrifugo:v5
    container_name: centrifugo
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8000:8000"
    environment:
      CENTRIFUGO_TOKEN_HMAC_SECRET_KEY: ${CENTRIFUGO_TOKEN_HMAC_SECRET_KEY}
      CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
      CENTRIFUGO_ADMIN_PASSWORD: ${CENTRIFUGO_ADMIN_PASSWORD}
      CENTRIFUGO_ADMIN_SECRET: ${CENTRIFUGO_ADMIN_SECRET}
      CENTRIFUGO_ADMIN: "true"
    volumes:
      - ./data:/centrifugo/data
    restart: unless-stopped
