services:
  openitcockpit:
    image: openitcockpit/openitcockpit:latest
    container_name: openitcockpit
    ports:
      - "80:80"
      - "443:443"
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./data/mysql:/var/lib/mysql
      - ./data/grafana:/var/lib/grafana
      - ./data/influxdb:/var/lib/influxdb
      - ./data/openitcockpit:/opt/openitcockpit/etc
      - ./data/naemon:/etc/naemon
      - ./data/nagvis-etc:/opt/openitcockpit/nagvis/etc
      - ./data/nagvis-userfiles:/opt/openitcockpit/nagvis/share/userfiles
      - ./data/prometheus:/var/lib/prometheus
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped
