manifestVersion: 1.1
id: openitcockpit
category: system-monitoring
name: openITCOCKPIT
version: latest
tagline: Manage Nagios, Naemon, and Prometheus with a graphical web interface.
description: Manage Nagios, Naemon, and Prometheus with a graphical web interface.
  Monitor servers, containers, and cloud environments with a unified agent and custom
  dashboards.
developer: openITCOCKPIT
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://openitcockpit.io?utm_source=awesome-docker-compose.com
repo: https://github.com/openITCOCKPIT/openITCOCKPIT
support: https://docs.openitcockpit.io/en/installation/docker/
