services:
  db:
    image: mongo:6
    restart: always
    volumes:
      - ./data/db:/data/db

  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    environment:
      - API_ENDPOINT=http://localhost:8080
      - CLIENT_ENDPOINT=http://localhost:3000
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - MONGO_ENDPOINT=mongodb://db:27017/your_spotify
    depends_on:
      - db

  client:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://localhost:8080
