manifestVersion: 1.1
id: your-spotify
category: internet-tool
name: Your Spotify
version: '6'
tagline: Host your own personal dashboard to track music listening habits.
description: Host your own personal dashboard to track music listening habits. Import
  past data, view detailed statistics, and keep full ownership of your audio history.
developer: Yooooomi
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/Yooooomi/your_spotify?utm_source=awesome-docker-compose.com
repo: https://github.com/Yooooomi/your_spotify
support: https://github.com/Yooooomi/your_spotify#installation
