manifestVersion: 1.1
id: apprise
category: notification
name: Apprise
version: latest
tagline: Send asynchronous push notifications to hundreds of services using a single,
  lightweight library.
description: Send asynchronous push notifications to hundreds of services using a
  single, lightweight library. Support attachments, custom routing, and CLI integration.
developer: caronc
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/caronc/apprise?utm_source=localhost
repo: https://github.com/caronc/apprise
support: https://github.com/caronc/apprise
