manifestVersion: 1.1
id: alerta
category: system-monitoring
name: Alerta
version: 14-alpine
tagline: Consolidate alerts from any monitoring tool into a single view.
description: Consolidate alerts from any monitoring tool into a single view. Automatically
  de-duplicate and correlate events to reduce noise. Integrates with your stack.
developer: alerta
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://alerta.io?utm_source=localhost
repo: https://github.com/alerta/alerta
support: https://github.com/alerta/docker-alerta
