manifestVersion: 1.1
id: microbin
category: pastebin
name: MicroBin
version: latest
tagline: Share, transfer, and protect your files with a self-hosted web application.
description: Share, transfer, and protect your files with a self-hosted web application.
  Enjoy URL redirection, automatic file expiry, and strong encryption levels.
developer: szabodanika
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://microbin.eu?utm_source=localhost
repo: https://github.com/szabodanika/microbin
support: https://github.com/szabodanika/microbin/blob/master/compose.yaml
