manifestVersion: 1.1
id: dumbterm
category: remote-access
name: DumbTerm
version: latest
tagline: Create and embed interactive terminal simulations for your website or product
  demos.
description: Create and embed interactive terminal simulations for your website or
  product demos. Guide users through command-line processes with a simple interface.
developer: DumbWareio
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://dumbterm.dumbware.io?utm_source=localhost
repo: https://github.com/DumbWareio/DumbTerm
support: https://github.com/DumbWareio/DumbTerm#quick-start
