manifestVersion: 1.1
id: excalidash
category: diagraming-and-canvas
name: ExcaliDash
version: latest
tagline: Create a self-hosted dashboard to organize your Excalidraw drawings.
description: Create a self-hosted dashboard to organize your Excalidraw drawings.
  Enable real-time collaboration, multi-user authentication, and scoped sharing for
  your team.
developer: ZimengXiong
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/ZimengXiong/ExcaliDash?utm_source=awesome-docker-compose.com
repo: https://github.com/ZimengXiong/ExcaliDash
support: https://github.com/ZimengXiong/ExcaliDash#installation
