manifestVersion: 1.1
id: cadvisor
category: container-management
name: Cadvisor
version: v0.49.0
tagline: Collect, aggregate, and export detailed data on container resource usage
  and performance.
description: Collect, aggregate, and export detailed data on container resource usage
  and performance. Get historical usage, network stats, and more to optimize your
  containers.
developer: google
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/google/cadvisor?utm_source=localhost
repo: https://github.com/google/cadvisor
support: https://github.com/google/cadvisor#quick-start-running-cadvisor-in-a-docker-container
