manifestVersion: 1.1
id: reitti
category: map-and-gps
name: Reitti
version: latest
tagline: Self-host your location data for complete privacy.
description: Self-host your location data for complete privacy. Automatically detect
  visits, analyze trips, and transform your movements into shareable travel stories.
developer: dedicatedcode
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.dedicatedcode.com/projects/reitti?utm_source=localhost
repo: https://github.com/dedicatedcode/reitti
support: https://github.com/dedicatedcode/reitti#docker-deployment
