manifestVersion: 1.1
id: rgit
category: git-server
name: rgit
version: latest
tagline: View your git repositories with a blazingly fast web interface.
description: View your git repositories with a blazingly fast web interface. Built
  in Rust, it uses efficient metadata storage and on-demand loading for superior performance.
developer: w4
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/w4/rgit?utm_source=localhost
repo: https://github.com/w4/rgit
support: https://github.com/w4/rgit#docker
