services:
  pigallery2:
    image: bpatrik/pigallery2:latest
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - ./config:/app/data/config
      - ./db-data:/app/data/db
      - ./images:/app/data/images:ro
      - ./tmp:/app/data/tmp
    ports:
      - 80:80
    restart: always
