manifestVersion: 1.1
id: pigallery-2
category: photo-server
name: Pigallery 2
version: latest
tagline: Build a speedy, self-hosted photo gallery directly from your file directories.
description: Build a speedy, self-hosted photo gallery directly from your file directories.
  Designed for Raspberry Pi and other low-power devices for efficient photo management.
developer: bpatrik
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://bpatrik.github.io/pigallery2?utm_source=localhost
repo: https://github.com/bpatrik/pigallery2
support: https://github.com/bpatrik/pigallery2/blob/master/docker/README.md
