manifestVersion: 1.1
id: inspircd
category: irc
name: InspIRCd
version: latest
tagline: Build and manage custom chat networks with a lightweight, modular C++ server.
description: Build and manage custom chat networks with a lightweight, modular C++
  server. Tune features easily, ensure high stability, and maintain robust security.
developer: inspircd
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.inspircd.org?utm_source=awesome-docker-compose.com
repo: https://github.com/inspircd/inspircd
support: https://github.com/inspircd/docker
