manifestVersion: 1.1
id: palmr
category: quick-file-transfer
name: Palmr
version: latest
tagline: Host your own secure file-sharing platform.
description: Host your own secure file-sharing platform. Upload, manage, and share
  files with password protection, custom links, and zero tracking or artificial limits.
developer: kyantech
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/kyantech/Palmr?utm_source=awesome-docker-compose.com
repo: https://github.com/kyantech/Palmr
support: https://github.com/kyantech/Palmr
