manifestVersion: 1.1
id: movim
category: social-network-and-forums
name: Movim
version: latest
tagline: Bring your chats, blogs, and video calls into one secure, decentralized platform.
description: Bring your chats, blogs, and video calls into one secure, decentralized
  platform. Connect across devices using standard protocols without compromising privacy.
developer: movim
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://movim.eu?utm_source=awesome-docker-compose.com
repo: https://github.com/movim/movim
support: https://github.com/movim/movim/blob/master/podman-compose.yml
