manifestVersion: 1.1
id: otobo
category: ticketing
name: OTOBO
version: latest
tagline: Automate routine tasks and manage IT, customer, and enterprise services efficiently.
description: Automate routine tasks and manage IT, customer, and enterprise services
  efficiently. Use a modular, open-source platform to reduce costs and improve support.
developer: RotherOSS
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://otobo.io?utm_source=awesome-docker-compose.com
repo: https://github.com/RotherOSS/otobo
support: https://github.com/RotherOSS/otobo-docker
