manifestVersion: 1.1
id: feedpushr
category: rss
name: feedpushr
version: latest
tagline: Manage feed subscriptions via a Web UI and API.
description: Manage feed subscriptions via a Web UI and API. Apply custom filters
  and use conditional logic to push new articles to various outputs like HTTP, email,
  and more.
developer: ncarlier
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/ncarlier/feedpushr?utm_source=awesome-docker-compose.com
repo: https://github.com/ncarlier/feedpushr
support: https://github.com/ncarlier/feedpushr#installation
