manifestVersion: 1.1
id: troddit
category: internet-tool
name: Troddit
version: latest
tagline: Enhance your browsing experience with customizable grid views, single-column
  modes, and galleries.
description: Enhance your browsing experience with customizable grid views, single-column
  modes, and galleries. Log in securely to vote, comment, and view your subreddits.
developer: burhan-syed
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.troddit.com?utm_source=localhost
repo: https://github.com/burhan-syed/troddit
support: https://github.com/burhan-syed/troddit#docker
