manifestVersion: 1.1
id: pg-back-web
category: database-backup
name: PG Back Web
version: latest
tagline: Manage PostgreSQL backups with an intuitive web interface.
description: Manage PostgreSQL backups with an intuitive web interface. Automate schedules,
  monitor status, store on S3 or locally, and restore with a single click.
developer: eduardolat
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/eduardolat/pgbackweb?utm_source=awesome-docker-compose.com
repo: https://github.com/eduardolat/pgbackweb
support: https://github.com/eduardolat/pgbackweb#installation
