manifestVersion: 1.1
id: cryptpad
category: office-suite
name: Cryptpad
version: latest
tagline: Create and edit documents, spreadsheets, and kanban boards in real-time.
description: Create and edit documents, spreadsheets, and kanban boards in real-time.
  Share securely with end-to-end encryption. No account required for collaborators.
developer: cryptpad
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://cryptpad.org?utm_source=awesome-docker-compose.com
repo: https://github.com/cryptpad/cryptpad
support: https://docs.cryptpad.org/en/admin_guide/installation.html#docker
