manifestVersion: 1.1
id: fail2ban-linuxserver-io
category: firewall
name: Fail2ban (LinuxServer.io)
version: latest
tagline: Monitor server logs for repeated failed login attempts.
description: Monitor server logs for repeated failed login attempts. Automatically
  update firewall rules to ban offending IP addresses and secure your services.
developer: fail2ban
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/fail2ban/fail2ban?utm_source=awesome-docker-compose.com
repo: https://github.com/fail2ban/fail2ban
support: https://github.com/fail2ban/fail2ban
