manifestVersion: 1.1
id: matomo
category: analytics
name: Matomo
version: '10.11'
tagline: Gain full control of your website data with an ethical analytics platform.
description: Gain full control of your website data with an ethical analytics platform.
  Track 100% of traffic accurately while protecting user privacy and ensuring compliance.
developer: matomo-org
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://matomo.org?utm_source=localhost
repo: https://github.com/matomo-org/matomo
support: https://github.com/matomo-org/docker
