manifestVersion: 1.1
id: teedy
category: document-management
name: Teedy
version: latest
tagline: Store, organize, and retrieve your files with a lightweight document management
  system.
description: Store, organize, and retrieve your files with a lightweight document
  management system. Find text inside images and PDFs using built-in OCR technology.
developer: sismics
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://teedy.io?utm_source=localhost
repo: https://github.com/sismics/docs
support: https://github.com/sismics/docs#install-with-docker
