manifestVersion: 1.1
id: wbo
category: diagraming-and-canvas
name: WBO
version: latest
tagline: Sketch new ideas together on a free, open-source online drawing tool.
description: Sketch new ideas together on a free, open-source online drawing tool.
  Collaborate in real time on a shared virtual board that is always saved.
developer: lovasoa
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://wbo.ophir.dev?utm_source=localhost
repo: https://github.com/lovasoa/whitebophir
support: https://github.com/lovasoa/whitebophir#running-your-own-instance-of-wbo
