manifestVersion: 1.1
id: tooljet
category: low-code
name: ToolJet
version: '13'
tagline: Create secure, full-stack internal applications 10x faster using an AI-powered
  builder.
description: Create secure, full-stack internal applications 10x faster using an AI-powered
  builder. Automate workflows and connect to any data source with ease.
developer: ToolJet
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.tooljet.com?utm_source=localhost
repo: https://github.com/ToolJet/ToolJet
support: https://docs.tooljet.com/docs/setup/docker/
