services:
  solr:
    image: solr:9
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - ./solr-data:/var/solr
    command:
      - solr-precreate
      - gettingstarted
    restart: unless-stopped
