services:
  proxy:
    image: reallibrephotos/librephotos-proxy:latest
    container_name: librephotos-proxy
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./data/protected_media:/protected_media

  db:
    image: postgres:13
    container_name: librephotos-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    command: postgres -c shared_buffers=256MB -c max_connections=200

  frontend:
    image: reallibrephotos/librephotos-frontend:latest
    container_name: librephotos-frontend
    restart: unless-stopped

  backend:
    image: reallibrephotos/librephotos:latest
    container_name: librephotos-backend
    restart: unless-stopped
    volumes:
      - ./data/photos:/data
      - ./data/protected_media:/protected_media
      - ./data/logs:/logs
      - ./data/cache:/root/.cache
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - BACKEND_HOST=librephotos-backend
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_BACKEND=postgresql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAPBOX_API_KEY=${MAPBOX_API_KEY}
      - TZ=UTC
    depends_on:
      - db
      - redis

  image-similarity:
    image: reallibrephotos/image-similarity:latest
    container_name: librephotos-image-similarity
    restart: unless-stopped

  redis:
    image: redis:6
    container_name: librephotos-redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
