manifestVersion: 1.1
id: librephotos
category: photo-server
name: LibrePhotos
version: latest
tagline: Manage your entire photo library on your own server.
description: Manage your entire photo library on your own server. Get powerful AI
  organization, support for all file types, and access your memories from any device.
developer: LibrePhotos
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://docs.librephotos.com?utm_source=awesome-docker-compose.com
repo: https://github.com/LibrePhotos/librephotos
support: https://docs.librephotos.com/docs/installation/standard-install/
