manifestVersion: 1.1
id: meelo
category: music-server
name: Meelo
version: latest
tagline: Take control of your audio library with a self-hosted music server.
description: Take control of your audio library with a self-hosted music server. Manage
  multiple album versions, track rare B-sides, and integrate music videos easily.
developer: Arthi-chaud
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://arthi-chaud.github.io/Meelo?utm_source=awesome-docker-compose.com
repo: https://github.com/Arthi-chaud/Meelo
support: https://arthi-chaud.github.io/Meelo/setup/tldr/
