manifestVersion: 1.1
id: jupyterlab
category: ide-and-tools
name: JupyterLab
version: latest
tagline: Build shareable documents with code, text, and rich visualizations.
description: Build shareable documents with code, text, and rich visualizations. Use
  a flexible, extensible, and feature-rich environment for interactive data science.
developer: jupyter
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://jupyterlab.readthedocs.io?utm_source=localhost
repo: https://github.com/jupyter/docker-stacks
support: https://jupyter-docker-stacks.readthedocs.io/en/latest/
