manifestVersion: 1.1
id: self-hosted-livesync
category: knowledge-management
name: Self-hosted LiveSync
version: '3'
tagline: Keep your notes synchronized with a self-hosted solution.
description: Keep your notes synchronized with a self-hosted solution. Use CouchDB,
  object storage, or WebRTC for secure, private, and encrypted syncing.
developer: vrtmrz
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/vrtmrz/obsidian-livesync?utm_source=localhost
repo: https://github.com/vrtmrz/obsidian-livesync
support: https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/setup_own_server.md
