manifestVersion: 1.1
id: nginx-proxy-manager
category: web-server
name: Nginx Proxy Manager
version: latest
tagline: Easily manage Nginx proxy hosts with a powerful web UI.
description: Easily manage Nginx proxy hosts with a powerful web UI. Secure your services
  with free, automatic SSL certificates from Let's Encrypt. Ideal for home networks.
developer: NginxProxyManager
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://nginxproxymanager.com?utm_source=localhost
repo: https://github.com/NginxProxyManager/nginx-proxy-manager
support: https://nginxproxymanager.com/guide/
