manifestVersion: 1.1
id: appflowy
category: project-management
name: Appflowy
version: latest
tagline: Bring projects and teams together in a secure workspace.
description: Bring projects and teams together in a secure workspace. Use local AI
  models, work offline, and self-host your data to maintain complete privacy and control.
developer: AppFlowy-IO
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://appflowy.com?utm_source=awesome-docker-compose.com
repo: https://github.com/AppFlowy-IO/appflowy
support: https://docs.appflowy.io/docs/appflowy/install-appflowy/installation-methods/installing-with-docker
