manifestVersion: 1.1
id: svix
category: api-management
name: Svix
version: latest
tagline: Send simple, secure, and scalable webhooks.
description: Send simple, secure, and scalable webhooks. Get automatic retries, robust
  security, and an embeddable portal for your users. Integrate in minutes.
developer: svix
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.svix.com?utm_source=awesome-docker-compose.com
repo: https://github.com/svix/svix-webhooks
support: https://github.com/svix/svix-webhooks#docker
