services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=traduora
      - MYSQL_USER=traduora
      - MYSQL_PASSWORD=${DB_PASSWORD}

  app:
    image: everco/ever-traduora:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TRADUORA_URL=http://localhost:8080
      - TRADUORA_SECRET=${TRADUORA_SECRET}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=traduora
      - DB_USER=traduora
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
