manifestVersion: 1.1
id: docmost
category: knowledge-management
name: Docmost
version: latest
tagline: Deploy a secure, on-premise wiki for full data control.
description: Deploy a secure, on-premise wiki for full data control. Manage team knowledge
  with real-time collaboration, SSO, MFA, and granular permissions. Meets ITAR & GDPR.
developer: docmost
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://docmost.com?utm_source=awesome-docker-compose.com
repo: https://github.com/docmost/docmost
support: https://docmost.com/docs/installation/
