services:
  server:
    image: radrootllc/karaoke-eternal:latest
    container_name: karaoke-eternal
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - TZ=Etc/UTC
    volumes:
      - ./data:/data
      - ./media:/media
