manifestVersion: 1.1
id: karaoke-eternal
category: media-server
name: Karaoke Eternal
version: latest
tagline: Host unforgettable karaoke parties with a fully self-hosted system.
description: Host unforgettable karaoke parties with a fully self-hosted system. Guests
  can easily find and queue songs directly from their mobile browsers using QR codes.
developer: bhj
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.karaoke-eternal.com?utm_source=localhost
repo: https://github.com/bhj/KaraokeEternal
support: https://www.karaoke-eternal.com/docs/karaoke-eternal-server/
