services:
  psitransfer:
    image: psitrax/psitransfer
    container_name: psitransfer
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    environment:
      - PSITRANSFER_ADMIN_PASS=${PSITRANSFER_ADMIN_PASS}
      - PSITRANSFER_UPLOAD_DIR=/data
