manifestVersion: 1.1
id: grocy
category: inventory-management
name: Grocy
version: latest
tagline: Track groceries, plan daily meals, and manage household chores with a self-hosted
  system.
description: Track groceries, plan daily meals, and manage household chores with a
  self-hosted system. Monitor inventory levels and reduce food waste effortlessly.
developer: grocy
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://grocy.info?utm_source=awesome-docker-compose.com
repo: https://github.com/grocy/grocy
support: https://github.com/linuxserver/docker-grocy
