manifestVersion: 1.1
id: backup-all-mysql
category: database-backup
name: backup-all-mysql
version: latest
tagline: Use this Docker image to schedule and automate MySQL database backups.
description: Use this Docker image to schedule and automate MySQL database backups.
  Configure intervals, delays, and connection parameters easily with environment variables.
developer: dsteinkopf
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/dsteinkopf/backup-all-mysql?utm_source=awesome-docker-compose.com
repo: https://github.com/dsteinkopf/backup-all-mysql
support: https://github.com/dsteinkopf/backup-all-mysql#setup
