manifestVersion: 1.1
id: immich-kiosk
category: photo-server
name: Immich Kiosk
version: latest
tagline: Create custom photo slideshows for TVs, tablets, or browsers.
description: Create custom photo slideshows for TVs, tablets, or browsers. This tool
  offers a responsive design, simple Docker setup, and URL-based controls.
developer: damongolding
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://immichkiosk.app?utm_source=awesome-docker-compose.com
repo: https://github.com/damongolding/immich-kiosk
support: https://github.com/damongolding/immich-kiosk#installation
