manifestVersion: 1.1
id: nxs-backup
category: backup
name: nxs-backup
version: latest
tagline: Create discrete or incremental backups for files and databases like MySQL,
  PostgreSQL, and MongoDB.
description: Create discrete or incremental backups for files and databases like MySQL,
  PostgreSQL, and MongoDB. Get notified via email or webhooks. Runs on any Linux system.
developer: nixys
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://nxs-backup.io?utm_source=awesome-docker-compose.com
repo: https://github.com/nixys/nxs-backup
support: https://github.com/nixys/nxs-backup#docker-compose
