services:
  hemmelig:
    image: hemmeligapp/hemmelig:latest
    container_name: hemmelig
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: hemmelig_redis
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
