manifestVersion: 1.1
id: homepage
category: personal-dashboard
name: Homepage
version: latest
tagline: Build a modern, fast, and secure application dashboard.
description: Build a modern, fast, and secure application dashboard. Integrate over
  100 services and customize everything with simple YAML files or docker labels.
developer: gethomepage
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://gethomepage.dev?utm_source=awesome-docker-compose.com
repo: https://github.com/gethomepage/homepage
support: https://gethomepage.dev/installation/docker/
