manifestVersion: 1.1
id: pinepods
category: podcasting
name: PinePods
version: latest
tagline: Manage and listen to podcasts across all devices with a lightning-fast, self-hosted
  server.
description: Manage and listen to podcasts across all devices with a lightning-fast,
  self-hosted server. Enjoy universal sync, offline support, and multi-user access.
developer: madeofpendletonwool
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.pinepods.online?utm_source=awesome-docker-compose.com
repo: https://github.com/madeofpendletonwool/PinePods
support: https://www.pinepods.online/docs/intro
