manifestVersion: 1.1
id: feedcord
category: rss
name: FeedCord
version: latest
tagline: Automatically deliver updates from RSS and YouTube feeds to your Discord
  server.
description: Automatically deliver updates from RSS and YouTube feeds to your Discord
  server. This self-hosted tool is simple to configure and run using Docker.
developer: Qolors
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/Qolors/FeedCord?utm_source=localhost
repo: https://github.com/Qolors/FeedCord
support: https://github.com/Qolors/FeedCord#setting-up-docker-composeyaml
