services:
  gerbera:
    image: gerbera/gerbera:latest
    container_name: gerbera
    network_mode: host
    volumes:
      - ./content:/content
      - ./data:/var/run/gerbera
    environment:
      - TZ=Etc/UTC
    restart: unless-stopped
