manifestVersion: 1.1
id: coolify
category: paas
name: Coolify
version: latest
tagline: Deploy applications, databases, and services to your own server.
description: Deploy applications, databases, and services to your own server. This
  open-source platform offers Git integration, free SSL certificates, and automatic
  backups.
developer: coollabsio
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://coolify.io?utm_source=awesome-docker-compose.com
repo: https://github.com/coollabsio/coolify
support: https://github.com/coollabsio/coolify/blob/v4.x/docker-compose.prod.yml
