manifestVersion: 1.1
id: emqx
category: internet-of-things-iot
name: EMQX
version: latest
tagline: Connect, process, and stream real-time data from millions of IoT devices
  to any cloud or AI platform.
description: Connect, process, and stream real-time data from millions of IoT devices
  to any cloud or AI platform. Scale massive workloads with sub-millisecond latency.
developer: emqx
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.emqx.com?utm_source=localhost
repo: https://github.com/emqx/emqx
support: https://docs.emqx.com/en/emqx/latest/deploy/install-docker.html
