manifestVersion: 1.1
id: mailcow
category: email-server
name: mailcow
version: '1.23'
tagline: Deploy a complete, containerized email server suite.
description: Deploy a complete, containerized email server suite. Manage domains,
  secure communications with built-in encryption, and integrate external authentication.
developer: mailcow
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://mailcow.email?utm_source=localhost
repo: https://github.com/mailcow/mailcow-dockerized
support: https://docs.mailcow.email/getstarted/install/
