manifestVersion: 1.1
id: planka
category: project-management
name: Planka
version: master
tagline: Manage agile projects with a self-hosted Kanban board.
description: Manage agile projects with a self-hosted Kanban board. Collaborate in
  real-time, organize tasks visually, and maintain complete control over your data.
developer: plankanban
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://planka.app?utm_source=awesome-docker-compose.com
repo: https://github.com/plankanban/planka
support: https://docs.planka.cloud/docs/category/docker
