manifestVersion: 1.1
id: mealie
category: recipe-management
name: Mealie
version: latest
tagline: Build a self-hosted recipe collection for your household.
description: Build a self-hosted recipe collection for your household. Import recipes
  from the web, scale ingredients, and plan meals with an intuitive interface.
developer: mealie-recipes
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://mealie.io?utm_source=localhost
repo: https://github.com/mealie-recipes/mealie
support: https://docs.mealie.io/documentation/getting-started/installation/installation-checklist/
