manifestVersion: 1.1
id: dnote
category: note-taking-and-editor
name: Dnote
version: 14-alpine
tagline: Quickly save commands, snippets, and insights from your terminal.
description: Quickly save commands, snippets, and insights from your terminal. Find
  them instantly with full-text search and sync across devices with a self-hosted
  server.
developer: dnote
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.getdnote.com?utm_source=localhost
repo: https://github.com/dnote/dnote
support: https://github.com/dnote/dnote#server-optional
