manifestVersion: 1.1
id: drupal
category: cms
name: Drupal
version: '10'
tagline: Build scalable digital experiences with a fully composable, open-source CMS.
description: Build scalable digital experiences with a fully composable, open-source
  CMS. Utilize integrated AI tools, visual page building, and enterprise-grade security.
developer: Awesome Docker Compose
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.drupal.org?utm_source=awesome-docker-compose.com
repo: https://awesome-docker-compose.com/drupal
support: https://awesome-docker-compose.com/drupal
