services:
  couchdb:
    image: couchdb:3
    restart: unless-stopped
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./couchdb-data:/opt/couchdb/data

  cozy:
    image: cozy/cozy-stack:latest
    restart: unless-stopped
    depends_on:
      - couchdb
    ports:
      - 8080:8080
    environment:
      - COUCHDB_URL=http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@couchdb:5984/
    volumes:
      - ./cozy-config:/etc/cozy
      - ./cozy-data:/usr/local/cozy-stack
    command: serve --host 0.0.0.0
