services:
  sish:
    image: antoniomika/sish:latest
    container_name: sish
    restart: unless-stopped
    ports:
      - "2222:2222"
      - "80:80"
      - "443:443"
    command:
      - -sish.domain=${SISH_DOMAIN}
      - -sish.password=${SISH_PASSWORD}
      - -sish.keys-directory=/pubkeys
      - -sish.pk-directory=/keys
      - -sish.https-certificate-directory=/ssl
      - -sish.http=true
      - -sish.https=true
      - -sish.log-to-client=true
      - -sish.bind-random-ports=false
    volumes:
      - ./data/keys:/keys
      - ./data/pubkeys:/pubkeys
      - ./data/ssl:/ssl
