services:
  budge:
    image: lscr.io/linuxserver/budge:latest
    container_name: budge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 8080:8080
    restart: unless-stopped
