services:
  everydocs:
    image: jonashellmann/everydocs:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./storage:/app/storage
      - ./db:/app/db
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
