manifestVersion: 1.1
id: everydocs
category: document-management
name: EveryDocs
version: latest
tagline: Manage private documents digitally.
description: Manage private documents digitally. Upload PDFs, organize them into folders,
  extract text for full-text search, and keep your files securely encrypted.
developer: jonashellmann
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/jonashellmann/everydocs-core?utm_source=awesome-docker-compose.com
repo: https://github.com/jonashellmann/everydocs-core
support: https://github.com/jonashellmann/everydocs-core#installation
