services:
  picoshare:
    image: mtlynch/picoshare
    container_name: picoshare
    restart: unless-stopped
    ports:
      - "4001:4001"
    environment:
      - PS_SHARED_SECRET=${PS_SHARED_SECRET}
    volumes:
      - ./data:/data
