services:
  puter:
    container_name: puter
    image: ghcr.io/heyputer/puter:latest
    restart: unless-stopped
    ports:
      - "4100:4100"
    volumes:
      - ./config:/etc/puter
      - ./data:/var/puter
