manifestVersion: 1.1
id: puter
category: virtual-system
name: Puter
version: latest
tagline: Get a feature-rich internet OS for personal cloud storage, app development,
  or remote desktop management.
description: Get a feature-rich internet OS for personal cloud storage, app development,
  or remote desktop management. It's free, open-source, and self-hostable.
developer: HeyPuter
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://puter.com?utm_source=awesome-docker-compose.com
repo: https://github.com/HeyPuter/puter
support: https://github.com/HeyPuter/puter#-docker-compose
