manifestVersion: 1.1
id: calibre-web
category: e-books
name: Calibre-Web
version: latest
tagline: Turn your Calibre database into a responsive web interface.
description: Turn your Calibre database into a responsive web interface. Browse, read,
  and download eBooks, manage user permissions, and sync directly to your eReader.
developer: janeczku
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/janeczku/calibre-web?utm_source=localhost
repo: https://github.com/janeczku/calibre-web
support: https://github.com/linuxserver/docker-calibre-web
