manifestVersion: 1.1
id: ackee
category: analytics
name: Ackee
version: latest
tagline: Run a privacy-first analytics tool on your own server.
description: Run a privacy-first analytics tool on your own server. Get key insights
  like views, referrers, and durations in a minimal interface without using cookies.
developer: electerious
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://ackee.electerious.com?utm_source=localhost
repo: https://github.com/electerious/Ackee
support: https://github.com/electerious/Ackee/blob/master/docs/Get%20started.md#with-docker-compose
