manifestVersion: 1.1
id: tube-archivist
category: video-downloader
name: Tube Archivist
version: latest
tagline: Subscribe to channels, download videos, and build your own searchable media
  library.
description: Subscribe to channels, download videos, and build your own searchable
  media library. Access your favorite YouTube content offline through a simple web
  interface.
developer: tubearchivist
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://tubearchivist.com?utm_source=awesome-docker-compose.com
repo: https://github.com/tubearchivist/tubearchivist
support: https://github.com/tubearchivist/tubearchivist#installing
