manifestVersion: 1.1
id: squidex
category: cms
name: Squidex
version: latest
tagline: Centralize content management with an open-source headless CMS.
description: Centralize content management with an open-source headless CMS. Track
  version history, automate workflows, and integrate easily via REST and GraphQL APIs.
developer: Squidex
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://squidex.io?utm_source=awesome-docker-compose.com
repo: https://github.com/Squidex/squidex
support: https://docs.squidex.io/id-01-getting-started/installation/platforms/install-on-docker
