manifestVersion: 1.1
id: passbolt
category: password-manager
name: Passbolt
version: '10.11'
tagline: Securely manage and share credentials as a team.
description: Securely manage and share credentials as a team. This open source platform
  offers end-to-end encryption, granular controls, and flexible self-hosting options.
developer: passbolt
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.passbolt.com?utm_source=localhost
repo: https://github.com/passbolt/passbolt_api
support: https://github.com/passbolt/passbolt_docker
