manifestVersion: 1.1
id: txtdot
category: proxy
name: txtdot
version: latest
tagline: Experience a simplified web.
description: Experience a simplified web. This proxy strips pages to essential text
  and images, cutting data usage, blocking ads, and removing heavy scripts for faster
  loading.
developer: TempoWorks
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://txt.dc09.xyz?utm_source=awesome-docker-compose.com
repo: https://github.com/TempoWorks/txtdot
support: https://github.com/TempoWorks/txtdot/blob/main/docker-compose.yml
