manifestVersion: 1.1
id: minmon
category: network-monitoring
name: MinMon
version: latest
tagline: Get a lightweight monitoring and alarming solution for Linux.
description: Get a lightweight monitoring and alarming solution for Linux. Use a single
  binary and a simple TOML config file to set up checks, actions, and reports. No
  GUI or DB.
developer: flo-at
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/flo-at/minmon?utm_source=localhost
repo: https://github.com/flo-at/minmon
support: https://github.com/flo-at/minmon#docker-image
