manifestVersion: 1.1
id: mailu
category: email-server
name: Mailu
version: alpine
tagline: Host your own secure email server with this set of Docker images.
description: Host your own secure email server with this set of Docker images. Features
  include webmail, advanced routing, robust antispam, and comprehensive admin tools.
developer: mailu
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://mailu.io?utm_source=awesome-docker-compose.com
repo: https://github.com/mailu/mailu
support: https://setup.mailu.io
