manifestVersion: 1.1
id: medama
category: analytics
name: Medama
version: latest
tagline: Monitor website performance with real-time, privacy-first insights.
description: Monitor website performance with real-time, privacy-first insights. This
  self-hostable solution uses a lightweight tracker (<1KB) without cookies or IP addresses.
developer: medama-io
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://oss.medama.io?utm_source=localhost
repo: https://github.com/medama-io/medama
support: https://oss.medama.io/deployment/docker
