services:
  docking:
    image: ghcr.io/shipsaas/docking:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_TOKEN=${API_TOKEN}
    volumes:
      - ./storage:/app/storage
