manifestVersion: 1.1
id: docking
category: document-management
name: DocKing
version: latest
tagline: Offload document template management and PDF rendering to a dedicated microservice.
description: Offload document template management and PDF rendering to a dedicated
  microservice. Supports multiple engines, dynamic data, and asynchronous generation.
developer: shipsaas
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://docking.shipsaas.tech?utm_source=localhost
repo: https://github.com/shipsaas/docking
support: https://docking.shipsaas.tech/deployment/docker
