manifestVersion: 1.1
id: docker-android
category: virtual-system
name: Docker-Android
version: emulator_11.0
tagline: Run a complete Android emulator within a Docker container.
description: Run a complete Android emulator within a Docker container. Access the
  UI via a web browser with noVNC, and automate your app testing with popular frameworks.
developer: budtmo
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/budtmo/docker-android?utm_source=localhost
repo: https://github.com/budtmo/docker-android
support: https://github.com/budtmo/docker-android#quick-start
