manifestVersion: 1.1
id: lychee
category: photo-server
name: Lychee
version: latest
tagline: Manage your photo library on your own server.
description: Manage your photo library on your own server. Upload, organize, and securely
  share albums with full control over your data. Supports EXIF and password protection.
developer: LycheeOrg
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://lycheeorg.dev?utm_source=localhost
repo: https://github.com/LycheeOrg/Lychee
support: https://github.com/LycheeOrg/Lychee-Docker
