manifestVersion: 1.1
id: clearflask
category: poll-and-events
name: ClearFlask
version: latest
tagline: Collect customer feedback, prioritize features, and share your product roadmap.
description: Collect customer feedback, prioritize features, and share your product
  roadmap. This open-source platform helps you build products your users actually
  want.
developer: clearflask
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://clearflask.com?utm_source=awesome-docker-compose.com
repo: https://github.com/clearflask/clearflask
support: https://github.com/clearflask/clearflask/blob/master/clearflask-release/src/main/docker/compose/docker-compose.self-host.yml
