services:
  web:
    image: joseluisq/static-web-server:2
    container_name: static-web-server
    ports:
      - "8080:80"
    environment:
      - SERVER_PORT=80
      - SERVER_ROOT=/public
      - SERVER_BASIC_AUTH=${SERVER_BASIC_AUTH}
    volumes:
      - ./public:/public
    restart: unless-stopped
