services:
  goaway:
    image: pommee/goaway:latest
    container_name: goaway
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - ORIGIN=${APP_ORIGIN}
      - TZ=UTC
