manifestVersion: 1.1
id: opengist
category: pastebin
name: Opengist
version: latest
tagline: Host and share code snippets easily with this open-source, Git-powered pastebin.
description: Host and share code snippets easily with this open-source, Git-powered
  pastebin. Deploy quickly via Docker and manage your pastes with full version control.
developer: thomiceli
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://opengist.io?utm_source=localhost
repo: https://github.com/thomiceli/opengist
support: https://opengist.io/docs/installation/docker.html
