manifestVersion: 1.1
id: doplarr
category: arr
name: Doplarr
version: latest
tagline: Process media requests directly within Discord using modern slash commands.
description: Process media requests directly within Discord using modern slash commands.
  Enjoy a lightweight setup that ensures privacy by never reading message content.
developer: kiranshila
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://kiranshila.github.io/Doplarr?utm_source=localhost
repo: https://github.com/kiranshila/Doplarr
support: https://kiranshila.github.io/Doplarr/#/installation
