manifestVersion: 1.1
id: owncloud
category: cloud-storage
name: ownCloud
version: 10.15.0
tagline: Take control of your digital content.
description: Take control of your digital content. Securely sync, share, and collaborate
  on files with a platform built for data sovereignty and enterprise-grade security.
developer: owncloud
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://owncloud.com?utm_source=localhost
repo: https://github.com/owncloud/core
support: https://doc.owncloud.com/server/10.15/admin_manual/installation/docker/
