manifestVersion: 1.1
id: files-sharing
category: quick-file-transfer
name: Files Sharing
version: latest
tagline: Group your important documents, images, and media into convenient bundles.
description: Group your important documents, images, and media into convenient bundles.
  Share large files quickly and manage your existing collections from one dashboard.
developer: axeloz
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://filesharing.webinno.fr?utm_source=localhost
repo: https://github.com/axeloz/filesharing
support: https://github.com/axeloz/filesharing#installation
