manifestVersion: 1.1
id: appsmith
category: low-code
name: Appsmith
version: latest
tagline: Create and deploy internal tools rapidly.
description: Create and deploy internal tools rapidly. Connect to databases and APIs,
  design UIs with widgets, and extend functionality with full JavaScript control.
developer: appsmithorg
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.appsmith.com?utm_source=localhost
repo: https://github.com/appsmithorg/appsmith
support: https://docs.appsmith.com/getting-started/setup/installation-guides/docker
