services:
  archivebox:
    image: archivebox/archivebox:master
    command: server --quick-init 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - ALLOWED_HOSTS=*
      - MEDIA_MAX_SIZE=750m
      - SEARCH_BACKEND_ENGINE=sonic
      - SEARCH_BACKEND_HOST_NAME=sonic
      - SEARCH_BACKEND_PASSWORD=${SONIC_PASSWORD}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/data
    depends_on:
      - sonic
    networks:
      - archivebox_network

  archivebox_scheduler:
    image: archivebox/archivebox:master
    command: schedule --foreground
    environment:
      - ALLOWED_HOSTS=*
      - MEDIA_MAX_SIZE=750m
      - SEARCH_BACKEND_ENGINE=sonic
      - SEARCH_BACKEND_HOST_NAME=sonic
      - SEARCH_BACKEND_PASSWORD=${SONIC_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/data
    depends_on:
      - sonic
    networks:
      - archivebox_network

  sonic:
    image: valeriansaliou/sonic:v1.4.9
    expose:
      - 1491
    environment:
      - SEARCH_BACKEND_PASSWORD=${SONIC_PASSWORD}
    volumes:
      - ./etc/sonic.cfg:/etc/sonic.cfg
      - ./data/sonic:/var/lib/sonic/store
    networks:
      - archivebox_network

networks:
  archivebox_network:
    driver: bridge
