manifestVersion: 1.1
id: archivebox
category: archiving
name: ArchiveBox
version: master
tagline: A self-hosted solution to collect and save web pages offline.
description: A self-hosted solution to collect and save web pages offline. Import
  from browser history or bookmarks and save as HTML, PDF, media, and more.
developer: ArchiveBox
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://archivebox.io?utm_source=awesome-docker-compose.com
repo: https://github.com/ArchiveBox/ArchiveBox
support: https://github.com/ArchiveBox/ArchiveBox/blob/dev/docker-compose.yml
