manifestVersion: 1.1
id: asciinema
category: miscellaneous
name: asciinema
version: 15-alpine
tagline: Capture and share terminal sessions with a lightweight, text-based approach.
description: "Capture and share terminal sessions with a lightweight, text-based approach.\
  \ Forget blurry videos\u2014easily embed recordings and copy-paste text directly."
developer: asciinema
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://asciinema.org?utm_source=localhost
repo: https://github.com/asciinema/asciinema-server
support: https://docs.asciinema.org/manual/server/self-hosting/quick-start/
