manifestVersion: 1.1
id: portnote
category: network-monitoring
name: PortNote
version: latest
tagline: Manage your server and VM port usage with a simple web interface.
description: Manage your server and VM port usage with a simple web interface. Document
  assignments, prevent conflicts, and maintain an organized network infrastructure.
developer: crocofied
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/crocofied/PortNote?utm_source=localhost
repo: https://github.com/crocofied/PortNote
support: https://github.com/crocofied/PortNote#deployment
