manifestVersion: 1.1
id: mathesar
category: database-management
name: Mathesar
version: '14'
tagline: Provide a simple, spreadsheet-like UI for your PostgreSQL database.
description: Provide a simple, spreadsheet-like UI for your PostgreSQL database. This
  open-source tool is self-hosted, secure, and easy for anyone to use, no technical
  skills needed.
developer: mathesar-foundation
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://mathesar.org?utm_source=awesome-docker-compose.com
repo: https://github.com/mathesar-foundation/mathesar
support: https://docs.mathesar.org/latest/administration/install-via-docker-compose/
