services:
  flashpaper:
    image: ghcr.io/andrewpaglusch/flashpaper:latest
    container_name: flashpaper
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./data:/var/www/html/data
    environment:
      - BASE_URL=${BASE_URL}
