services:
  ytdl_material:
    image: tzahi12345/youtubedl-material:latest
    environment:
      ALLOW_CONFIG_MUTATIONS: 'true'
      ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
      ytdl_use_local_db: 'false'
      write_ytdl_config: 'true'
    restart: always
    depends_on:
      - ytdl-mongo-db
    volumes:
      - ./appdata:/app/appdata
      - ./audio:/app/audio
      - ./video:/app/video
      - ./subscriptions:/app/subscriptions
      - ./users:/app/users
    ports:
      - "17442:17442"

  ytdl-mongo-db:
    image: mongo:4
    logging:
      driver: "none"
    restart: always
    volumes:
      - ./db:/data/db
