manifestVersion: 1.1
id: koito
category: music-server
name: Koito
version: latest
tagline: Track your listening patterns, relay scrobbles to other sites, and automatically
  fetch rich metadata with this modern,...
description: Track your listening patterns, relay scrobbles to other sites, and automatically
  fetch rich metadata with this modern, themeable, open-source music server.
developer: gabehf
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://koito.io?utm_source=awesome-docker-compose.com
repo: https://github.com/gabehf/Koito
support: https://koito.io/reference/configuration/
