manifestVersion: 1.1
id: docspell
category: document-management
name: Docspell
version: 16-alpine
tagline: Manage digital documents from scanners and emails easily.
description: Manage digital documents from scanners and emails easily. Extract text
  using OCR, convert files to searchable PDFs, and find exactly what you need fast.
developer: eikek
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://docspell.org?utm_source=awesome-docker-compose.com
repo: https://github.com/eikek/docspell
support: https://docspell.org/docs/install/docker/
