services:
  grist:
    image: gristlabs/grist
    container_name: grist
    ports:
      - "8484:8484"
    volumes:
      - ./persist:/persist
    environment:
      - GRIST_SESSION_SECRET=${GRIST_SESSION_SECRET}
    restart: unless-stopped
