manifestVersion: 1.1
id: grist
category: office-suite
name: Grist
version: latest
tagline: Organize your data with a relational spreadsheet-database.
description: Organize your data with a relational spreadsheet-database. Build custom
  layouts, control access with granular permissions, and use Python-powered formulas.
developer: gristlabs
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.getgrist.com?utm_source=localhost
repo: https://github.com/gristlabs/grist-core
support: https://github.com/gristlabs/grist-core#using-grist
