manifestVersion: 1.1
id: koel
category: music-server
name: Koel
version: latest
tagline: Build a personal music streaming server featuring lossless audio, smart playlists,
  and mobile apps.
description: Build a personal music streaming server featuring lossless audio, smart
  playlists, and mobile apps. Manage metadata easily and sync across all your devices.
developer: koel
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://koel.dev?utm_source=awesome-docker-compose.com
repo: https://github.com/koel/koel
support: https://github.com/koel/docker
