manifestVersion: 1.1
id: booklore
category: e-books
name: BookLore
version: latest
tagline: Organize your digital books with automatic metadata, dynamic shelves, and
  a built-in web reader.
description: Organize your digital books with automatic metadata, dynamic shelves,
  and a built-in web reader. Sync reading progress across devices and share with family.
developer: booklore-app
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://booklore.org?utm_source=localhost
repo: https://github.com/booklore-app/booklore
support: https://booklore.org/docs/installation
