manifestVersion: 1.1
id: dokku
category: paas
name: Dokku
version: latest
tagline: Create a personal PaaS on any server.
description: Create a personal PaaS on any server. Push Heroku-compatible applications
  via Git and let Docker build and run them in isolated containers. No vendor lock-in.
developer: dokku
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://dokku.com?utm_source=localhost
repo: https://github.com/dokku/dokku
support: https://dokku.com/docs/getting-started/install/docker/
