manifestVersion: 1.1
id: prometheus
category: system-monitoring
name: Prometheus
version: latest
tagline: Monitor cloud-native systems with a dimensional data model and flexible query
  language.
description: Monitor cloud-native systems with a dimensional data model and flexible
  query language. Collect, store, and query metrics for powerful alerting and dashboards.
developer: prometheus
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://prometheus.io?utm_source=awesome-docker-compose.com
repo: https://github.com/prometheus/prometheus
support: https://prometheus.io/docs/prometheus/latest/installation/
