manifestVersion: 1.1
id: firefly-iii
category: budgeting
name: Firefly III
version: latest
tagline: Manage your money with a double-entry system.
description: Manage your money with a double-entry system. Import data from any source,
  automate entries with rules, and visualize spending with detailed reports.
developer: firefly-iii
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://firefly-iii.org?utm_source=awesome-docker-compose.com
repo: https://github.com/firefly-iii/firefly-iii
support: https://docs.firefly-iii.org/how-to/firefly-iii/installation/docker/
