manifestVersion: 1.1
id: itflow
category: ticketing
name: ITFlow
version: '10.11'
tagline: Consolidate client documentation, support tickets, and invoicing into one
  open-source platform.
description: Consolidate client documentation, support tickets, and invoicing into
  one open-source platform. Manage passwords, track assets, and automate billing easily.
developer: itflow-org
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://itflow.org?utm_source=awesome-docker-compose.com
repo: https://github.com/itflow-org/itflow
support: https://github.com/itflow-org/itflow-docker
