manifestVersion: 1.1
id: huginn
category: automation
name: Huginn
version: '5.7'
tagline: Build agents to perform automated tasks online.
description: Build agents to perform automated tasks online. Read the web, watch for
  events, and take actions on your behalf. A hackable, self-hosted alternative to
  IFTTT.
developer: huginn
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/huginn/huginn?utm_source=localhost
repo: https://github.com/huginn/huginn
support: https://github.com/huginn/huginn/blob/master/doc/docker/install.md
