manifestVersion: 1.1
id: immich
category: photo-server
name: Immich
version: release
tagline: Create a private, self-hosted photo and video library on your own server.
description: Create a private, self-hosted photo and video library on your own server.
  Automatically back up, organize, and search your media without sacrificing privacy.
developer: immich-app
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://immich.app?utm_source=localhost
repo: https://github.com/immich-app/immich
support: https://docs.immich.app/install/docker-compose/
