manifestVersion: 1.1
id: grimoire
category: bookmark-manager
name: Grimoire
version: latest
tagline: Conjure order from bookmark chaos.
description: Conjure order from bookmark chaos. Automatically fetches page titles,
  images, and content. Keep your links private with this open-source, self-hosted
  manager.
developer: goniszewski
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://grimoire.pro?utm_source=awesome-docker-compose.com
repo: https://github.com/goniszewski/grimoire
support: https://grimoire.pro/docs/getting-started/quick-start/
