services:
  dagu:
    image: ghcr.io/dagu-org/dagu:latest
    container_name: dagu
    ports:
      - "8080:8080"
    environment:
      - DAGU_HOST=0.0.0.0
      - DAGU_PORT=8080
      - DAGU_IS_BASICAUTH=1
      - DAGU_ADMIN_ID=${DAGU_ADMIN_ID}
      - DAGU_ADMIN_PASSWORD=${DAGU_ADMIN_PASSWORD}
    volumes:
      - ./dags:/home/dagu/dags
      - ./data:/home/dagu/.dagu
    restart: unless-stopped
