manifestVersion: 1.1
id: dagu
category: automation
name: Dagu
version: latest
tagline: Manage complex jobs with a powerful, local-first workflow engine.
description: Manage complex jobs with a powerful, local-first workflow engine. Define
  pipelines in simple YAML, run any script, and monitor everything via a built-in
  web UI.
developer: dagu-org
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://dagu.sh?utm_source=awesome-docker-compose.com
repo: https://github.com/dagu-org/dagu
support: https://docs.daguit.dev/getting-started/installation
