services:
  trudesk:
    image: polonel/trudesk:latest
    restart: always
    ports:
      - "8118:8118"
    environment:
      NODE_ENV: production
      TRUDESK_DOCKER: "true"
      TD_MONGODB_SERVER: mongodb
      TD_MONGODB_PORT: 27017
      TD_MONGODB_DATABASE: trudesk
      TD_MONGODB_USERNAME: root
      TD_MONGODB_PASSWORD: ${DB_ROOT_PASSWORD}
      TD_MONGODB_AUTHSOURCE: admin
    volumes:
      - ./uploads:/usr/src/trudesk/public/uploads
      - ./plugins:/usr/src/trudesk/plugins
      - ./backups:/usr/src/trudesk/backups
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: trudesk
    volumes:
      - ./mongo-data:/data/db
