services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm
      - DB_USER=romm
      - DB_PASS=${DB_PASSWORD}
      - REDIS_HOST=romm-redis
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY}
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET}
    volumes:
      - ./library:/romm/library
      - ./resources:/romm/resources
      - ./config:/romm/config
    ports:
      - 8080:8080
    depends_on:
      - romm-db
      - romm-redis

  romm-db:
    image: mariadb:10.11
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql

  romm-redis:
    image: redis:alpine
    container_name: romm-redis
    restart: unless-stopped
