manifestVersion: 1.1
id: flatnotes
category: note-taking-and-editor
name: flatnotes
version: latest
tagline: Create and manage notes using a simple folder of Markdown files.
description: Create and manage notes using a simple folder of Markdown files. This
  self-hosted web app offers a clean interface, powerful search, and requires no database.
developer: dullage
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://demo.flatnotes.io?utm_source=localhost
repo: https://github.com/dullage/flatnotes
support: https://github.com/dullage/flatnotes#self-hosted
