manifestVersion: 1.1
id: 13ft
category: internet-tool
name: 13ft
version: latest
tagline: Host your own server to bypass article paywalls and block intrusive ads.
description: Host your own server to bypass article paywalls and block intrusive ads.
  It mimics search engine crawlers to fetch full content for uninterrupted reading.
developer: wasi-master
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://github.com/wasi-master/13ft?utm_source=awesome-docker-compose.com
repo: https://github.com/wasi-master/13ft
support: https://github.com/wasi-master/13ft#using-docker
