services:
  myip:
    image: jason5ng32/myip:latest
    container_name: myip
    ports:
      - "18966:18966"
    environment:
      - IPINFO_API_TOKEN=${IPINFO_API_TOKEN}
      - BING_MAP_API_KEY=${BING_MAP_API_KEY}
    restart: unless-stopped
