manifestVersion: 1.1
id: myip
category: ip-and-domain
name: MyIP
version: latest
tagline: Instantly analyze any IP address.
description: Instantly analyze any IP address. Discover its location, owner, and reputation.
  Perfect for network administrators, security researchers, and curious users.
developer: jason5ng32
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://ipcheck.ing?utm_source=awesome-docker-compose.com
repo: https://github.com/jason5ng32/MyIP
support: https://github.com/jason5ng32/MyIP#using-docker
