services:
  audioserve:
    image: izderadicka/audioserve
    container_name: audioserve
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./audiobooks:/audiobooks
      - ./data:/home/audioserve/.audioserve
    environment:
      - AUDIOSERVE_SHARED_SECRET=${AUDIOSERVE_SHARED_SECRET}
    # The command argument specifies the collection directory inside the container
    command: /audiobooks
