manifestVersion: 1.1
id: nodebb
category: social-network-and-forums
name: NodeBB
version: '5.0'
tagline: Create engaging online communities using a mobile-first discussion platform.
description: Create engaging online communities using a mobile-first discussion platform.
  Enjoy real-time streaming, single sign-on, built-in chat, and robust SEO tools.
developer: NodeBB
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://nodebb.org?utm_source=awesome-docker-compose.com
repo: https://github.com/NodeBB/NodeBB
support: https://docs.nodebb.org/installing/cloud/docker/
