manifestVersion: 1.1
id: authentik
category: identity-and-access-management
name: Authentik
version: 16-alpine
tagline: Bring all authentication into one self-hosted, open-source platform.
description: Bring all authentication into one self-hosted, open-source platform.
  Customize every step with APIs and templates for ultimate flexibility and data control.
developer: goauthentik
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://goauthentik.io?utm_source=awesome-docker-compose.com
repo: https://github.com/goauthentik/authentik
support: https://docs.goauthentik.io/install-config/install/docker-compose/
