services:
  sickchill:
    image: sickchill/sickchill:latest
    container_name: sickchill
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data:/data
      - ./downloads:/downloads
      - ./tv:/tv
    ports:
      - 8081:8081
    restart: unless-stopped
