manifestVersion: 1.1
id: sickchill
category: video-downloader
name: SickChill
version: latest
tagline: Automatically find and download new episodes of your favorite TV shows and
  anime.
description: Automatically find and download new episodes of your favorite TV shows
  and anime. It searches torrents and Usenet, grabs subtitles, and organizes your
  library.
developer: SickChill
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://sickchill.github.io?utm_source=awesome-docker-compose.com
repo: https://github.com/SickChill/sickchill
support: https://github.com/SickChill/SickChill/wiki/Docker
