services:
  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    environment:
      NC_AUTH_JWT_SECRET: ${NC_AUTH_JWT_SECRET}
    ports:
      - "8080:8080"
    volumes:
      - ./nc_data:/usr/app/data
    restart: unless-stopped
