manifestVersion: 1.1
id: jelu
category: e-books
name: Jelu
version: latest
tagline: Track your reading history, manage to-read lists, and import data from Goodreads.
description: Track your reading history, manage to-read lists, and import data from
  Goodreads. Organize books with custom tags, view reading stats, and share reviews.
developer: bayang
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://bayang.github.io/jelu-web?utm_source=localhost
repo: https://github.com/bayang/jelu
support: https://bayang.github.io/jelu-web/installation/docker/
