manifestVersion: 1.1
id: filegator
category: storage-file-transfer
name: FileGator
version: latest
tagline: Manage files and folders using a free, self-hosted web application.
description: Manage files and folders using a free, self-hosted web application. Enjoy
  advanced features like drag-and-drop, zip support, and Amazon S3 integration.
developer: filegator
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://filegator.io?utm_source=localhost
repo: https://github.com/filegator/filegator
support: https://docs.filegator.io/install.html
