manifestVersion: 1.1
id: quickshare
category: quick-file-transfer
name: Quickshare
version: latest
tagline: Host your own file sharing platform with resumable uploads, QR code access,
  and cross-device compatibility for Linux, M...
description: Host your own file sharing platform with resumable uploads, QR code access,
  and cross-device compatibility for Linux, Mac, and Windows environments.
developer: ihexxa
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://ihexxa.github.io/quickshare.site?utm_source=awesome-docker-compose.com
repo: https://github.com/ihexxa/quickshare
support: https://github.com/ihexxa/quickshare#quick-start
