manifestVersion: 1.1
id: openttd
category: games
name: OpenTTD
version: latest
tagline: Construct intricate transport systems, manage cargo routes, and build profitable
  networks in this comprehensive open-so...
description: Construct intricate transport systems, manage cargo routes, and build
  profitable networks in this comprehensive open-source simulation game.
developer: OpenTTD
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://www.openttd.org?utm_source=awesome-docker-compose.com
repo: https://github.com/OpenTTD/OpenTTD
support: https://github.com/OpenTTD/OpenTTD
