services:
  remotely:
    image: immense/remotely:latest
    container_name: remotely
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/remotely-data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
