manifestVersion: 1.1
id: kopia
category: backup
name: Kopia
version: latest
tagline: Create fast, encrypted, and deduplicated backups on Windows, Mac, or Linux.
description: Create fast, encrypted, and deduplicated backups on Windows, Mac, or
  Linux. Use your preferred cloud storage with a GUI or CLI. Open-source and secure.
developer: kopia
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://kopia.io?utm_source=localhost
repo: https://github.com/kopia/kopia
support: https://kopia.io/docs/installation/#docker-images
