manifestVersion: 1.1
id: habittrove
category: habit-tracker
name: HabitTrove
version: latest
tagline: Build positive daily routines with a gamified tracking system.
description: Build positive daily routines with a gamified tracking system. Monitor
  your progress, stay motivated, and earn exciting rewards for completing your goals.
developer: dohsimpson
dependencies: []
gallery: []
path: /
defaultUsername: ''
deterministicPassword: false
torOnly: false
submitter: Hiveden
website: https://demo.habittrove.com?utm_source=localhost
repo: https://github.com/dohsimpson/HabitTrove
support: https://github.com/dohsimpson/HabitTrove#docker-deployment
